-- Seed: grupos_res1732 y servicios_res1732 (hoja 'Servicios' del Excel v3, 44 filas)

insert into grupos_res1732 (numeral, nombre, descripcion) values
  ('5', 'Todo los servicios', 'Los estándares y criterios que se desarrollan a continuación definen las condiciones mínimas que debe cumplir cada servicio de salud para ser habilitado. Están organizados por estándar y aplican de manera diferenciada según el tipo de prestador, el servicio a habilitar, su complejidad, modalidad y especificidad. En el proceso de autoevaluación, cada prestador debe revisar la totalidad de los criterios aquí contenidos e identificar cuáles le son aplicables de acuerdo con el o los servicios que va a habilitar.'),
  ('6.1', 'GRUPO CONSULTA EXTERNA', 'Descripción: Son los servicios en los que se ofrece orientación, diagnóstico, tratamiento o paliación. De acuerdo con el criterio médico y en el marco de su autonomía, la atención podrá tener carácter prioritario.

En los ambientes, áreas, o salas de procedimientos dependientes del servicio de consulta externa, no pueden permanecer pacientes que requieran observación o internación. Las áreas de observación son exclusivas de los servicios de urgencias.

El grupo incluye los siguientes servicios:

Consulta externa general
Consulta externa especializada
Vacunación
Seguridad y Salud en el trabajo'),
  ('6.2', 'GRUPO APOYO DIAGNÓSTICO Y COMPLEMENTACIÓN TERAPÉUTICA', 'Este grupo incluye los servicios de:

Terapias
Farmacéutico
Radiología odontológica
Imágenes diagnósticas
Métodos diagnósticos con imágenes obtenidas mediante equipos generadores de radiaciones ionizantes
Métodos diagnósticos con imágenes obtenidas mediante equipos generadores de radiaciones no ionizantes
Medicina nuclear
Radioterapia
Quimioterapia
Diagnóstico vascular
Hemodinamia e intervencionismo
Gestión pre transfusional
Toma de muestras de laboratorio clínico
Laboratorio clínico
Toma de muestras de cuello uterino y ginecológicas
Laboratorio de citologías cervico-uterinas
Laboratorio de histotecnología
Patología
Diálisis'),
  ('6.3', 'GRUPO INTERNACIÓN', 'Este grupo incluye los servicios de:

Servicio de hospitalización
Servicio de hospitalización paciente crónico
Servicio de cuidado básico neonatal
Servicio de cuidado intermedio neonatal
Servicio de cuidado intensivo neonatal
Servicio de cuidado intermedio pediátrico
Servicio de cuidado intensivo pediátrico
Servicio de cuidado intermedio adulto
Servicio de cuidado intensivo adultos
Servicio de hospitalización en salud mental o consumo de sustancias psicoactivas
Servicio de hospitalización parcial
Servicio para el cuidado básico del consumo de sustancias psicoactivas'),
  ('6.4', 'GRUPO QUIRURGICO', null),
  ('6.5', 'GRUPO ATENCIÓN INMEDIATA', null);

insert into servicios_res1732 (numeral, grupo_res1732_id, nombre, descripcion, estructura) values
  ('5', (select id from grupos_res1732 where numeral = '5'), 'Todo los servicios', 'Los estándares y criterios que se desarrollan a continuación definen las condiciones mínimas que debe cumplir cada servicio de salud para ser habilitado. Están organizados por estándar y aplican de manera diferenciada según el tipo de prestador, el servicio a habilitar, su complejidad, modalidad y especificidad. En el proceso de autoevaluación, cada prestador debe revisar la totalidad de los criterios aquí contenidos e identificar cuáles le son aplicables de acuerdo con el o los servicios que va a habilitar.', 'Aplica de forma diferenciada según el estándar, servicio, complejidad y modalidad; ver el detalle en cada estándar (Talento Humano, Infraestructura, Dotación, Medicamentos, Procesos Prioritarios, Historia Clínica y Registros, Interdependencia).'),
  ('6.1.1', (select id from grupos_res1732 where numeral = '6.1'), 'Consulta externa general', 'Servicio de consulta externa donde se ofrece orientación, diagnóstico, tratamiento o paliación por parte de profesionales de la salud, de acuerdo con el criterio médico y en el marco de su autonomía.', 'Complejidad: Baja. Modalidades de prestación: Intramural; Extramural: Unidad móvil, Jornada de Salud y Domiciliaria; Telemedicina – Categorías: Telexperticia, Telemonitoreo, Teleconsulta.'),
  ('6.1.2', (select id from grupos_res1732 where numeral = '6.1'), 'Consulta externa especializada', 'Hacen parte de este servicio, entre otras, las siguientes especialidades. Medicina alternativa y complementaria: Homeopática, Osteopática, Neuralterapéutica, Tradicional China, Naturopática, Ayurvédica. Terapias alternativas y complementarias: Bioenergética, Terapia con filtros, Terapias manuales.', 'Complejidad: Mediana. Modalidades de prestación: Intramural; Extramural: Unidad móvil, Jornada de Salud, Domiciliaria; Telemedicina – Categorías: Telexperticia, Telemonitoreo, Teleconsulta.'),
  ('6.1.3', (select id from grupos_res1732 where numeral = '6.1'), 'Vacunación', 'Servicio en el cual se intervienen a los usuarios mediante las acciones de vacunación, definidas por el Estado como parte de las prestaciones de salud pública para lograr la protección de la población, o solicitadas de forma particular por el médico tratante o por el usuario en su decisión de evitar enfermedades inmunoprevenibles.', 'Complejidad: Baja. Modalidades: Intramural; Extramural Unidad Móvil, Jornada de Salud y Domiciliaria.'),
  ('6.1.4', (select id from grupos_res1732 where numeral = '6.1'), 'Seguridad y salud en el trabajo', 'Es el servicio de salud donde se interroga y examina a un paciente, con el fin de monitorear la exposición a factores de riesgo laborales y determinar la existencia de consecuencias en la salud de las personas por dicha exposición. Se realizan valoraciones complementarias como apoyo al diagnóstico y forman parte de las evaluaciones médicas ocupacionales.', 'Complejidad: Mediana. Modalidades de prestación: Intramural, Extramural Unidad móvil y Jornada de Salud; Telemedicina - Categorías: Telexperticia.'),
  ('6.2.1', (select id from grupos_res1732 where numeral = '6.2'), 'Terapias', 'Son los servicios donde se realizan procedimientos de tratamiento y rehabilitación a fin de prevenir discapacidades y lograr la curación o paliación de las enfermedades o síntomas. Incluye: Fisioterapia o terapia física, fonoaudiología o terapia del lenguaje, terapia ocupacional y terapia respiratoria.', 'Complejidad: No aplica. Modalidades: Intramural; Extramural Unidad móvil, Jornada de Salud, Domiciliaria; Telemedicina – Categorías: Teleconcepto, Telemonitoreo, Teleconsulta.'),
  ('6.2.2', (select id from grupos_res1732 where numeral = '6.2'), 'Servicio farmacéutico', 'Es el servicio de atención en salud que apoya las actividades, procedimientos e intervenciones de carácter técnico, científico y administrativo, relacionados con los medicamentos y los dispositivos médicos utilizados en la promoción de la salud y la prevención, diagnóstico, tratamiento y rehabilitación de la enfermedad y paliación. Los prestadores de servicios de salud no pueden habilitar este servicio como único servicio en su portafolio.', 'Complejidades: Baja, mediana y alta. Baja complejidad: procesos generales (selección, adquisición, transporte, recepción, almacenamiento, conservación, control de fechas de vencimiento, cadena de frío, distribución, dispensación, uso, devolución, farmacovigilancia, educación). Mediana y alta: adicionalmente procesos especiales (atención farmacéutica, preparaciones magistrales/extemporáneas/estériles, nutriciones parenterales, mezcla de medicamentos oncológicos, radiofármacos, investigación clínica, entre otros). Modalidades de prestación: Intramural, Extramural domiciliaria; Telemedicina – Categoría: Teleconcepto.'),
  ('6.2.3', (select id from grupos_res1732 where numeral = '6.2'), 'Radiología odontológica', 'Es el servicio dedicado al diagnóstico de las enfermedades odontológicas, mediante el uso de métodos diagnósticos con imágenes obtenidas a través de radiaciones ionizantes.', 'Complejidad: No aplica. Modalidades de prestación: Intramural, Extramural: Unidad móvil; Telemedicina – Categorías: Teleconcepto.'),
  ('6.2.4', (select id from grupos_res1732 where numeral = '6.2'), 'Imágenes diagnósticas', 'Es el servicio dedicado al apoyo diagnóstico o tratamiento de las enfermedades mediante el uso de métodos diagnósticos con imágenes obtenidas a través de equipos generadores de radiaciones ionizantes o no ionizantes.', 'Complejidades: Baja, mediana y alta (radiaciones ionizantes); Mediana (radiaciones no ionizantes). Modalidades: Intramural (ionizantes y no ionizantes); Extramural Unidad móvil (ionizantes y no ionizantes, no aplica medio de contraste ni intervencionismo); Extramural Domiciliaria y Jornada de Salud (solo no ionizantes); Telemedicina – Categoría Teleconcepto (ionizantes en baja/mediana/alta y no ionizantes en mediana).'),
  ('6.2.5', (select id from grupos_res1732 where numeral = '6.2'), 'Medicina nuclear', 'Servicio en el que se realizan procedimientos diagnósticos o terapéuticos mediante fuentes no selladas de radiación constituidas por isótopos radiactivos, radiofármacos o radionúclidos de uso en humanos.', 'Complejidad: Alta. Modalidad de prestación: Intramural; Telemedicina – Categoría Teleconcepto.'),
  ('6.2.6', (select id from grupos_res1732 where numeral = '6.2'), 'Radioterapia', 'Servicio en el que se lleva a cabo tratamiento médico que hace uso de radiación ionizante con el fin de erradicar un volumen tumoral benigno o maligno y en patologías no tumorales.', 'Complejidad: Alta. Modalidades de prestación: Intramural; Telemedicina – Categoría Teleconcepto.'),
  ('6.2.7', (select id from grupos_res1732 where numeral = '6.2'), 'Quimioterapia', 'Servicio de administración de medicamentos oncológicos.', 'Complejidad: Alta. Modalidades de prestación: Intramural; Extramural Domiciliaria (aplica para los prestadores que cuenten con el servicio en la modalidad intramural); Telemedicina – Categoría Teleconcepto.'),
  ('6.2.8', (select id from grupos_res1732 where numeral = '6.2'), 'Diagnóstico vascular', 'Es el servicio que utiliza métodos y procedimientos para el diagnóstico de enfermedades o disfunciones del sistema cardiovascular y vascular periférico (venoso, arterial y linfático), de sus órganos o la demostración de sus procesos fisiológicos.', 'Complejidad: Mediana. Modalidades de prestación: Intramural; Telemedicina – Categoría Telemonitoreo.'),
  ('6.2.9', (select id from grupos_res1732 where numeral = '6.2'), 'Hemodinamia e intervencionismo', 'Es el servicio en el cual se realizan procedimientos diagnósticos y terapéuticos del sistema vascular, cardiovascular y no vascular mediante técnicas invasivas bajo visión angiográfica.', 'Complejidad: Alta. Modalidad de prestación: Intramural; Telemedicina – Categoría Teleconcepto.'),
  ('6.2.10', (select id from grupos_res1732 where numeral = '6.2'), 'Gestión pre transfusional', 'Servicio en el que se realizan procedimientos previos a la transfusión sanguínea, que incluye: la consecución, abastecimiento, almacenamiento y distribución de los componentes sanguíneos y la realización de las pruebas pre transfusionales, con el fin de asegurar la selección adecuada del componente sanguíneo a transfundir y su entrega al servicio en donde será transfundido el paciente. Los prestadores habilitarán este servicio para brindar apoyo a otros servicios de salud; no podrá habilitarse como servicio único.', 'Complejidad: No aplica. Modalidad de prestación: Intramural; Telemedicina – Categoría Teleconcepto.'),
  ('6.2.11', (select id from grupos_res1732 where numeral = '6.2'), 'Toma de muestras de laboratorio', 'Servicio en el cual se realiza la toma y recepción de muestras de origen humano, que serán remitidas para su procesamiento.', 'Complejidad: No aplica. Modalidades de prestación: Intramural, Extramural Unidad Móvil, Jornada de Salud y Domiciliaria.'),
  ('6.2.12', (select id from grupos_res1732 where numeral = '6.2'), 'Laboratorio clínico', 'Servicio en el cual se realizan procedimientos de análisis de especímenes biológicos de origen humano. En este servicio se podrá realizar toma de muestras de origen humano (en tal caso no será necesario habilitar el servicio de toma de muestras de laboratorio clínico). Cuando se realicen pruebas de inmunología para trasplantes debe garantizarse atención 24 horas para el procesamiento de las muestras.', 'Complejidad: No aplica. Modalidades de prestación: Intramural, Extramural Jornada de Salud y Unidad Móvil; Telemedicina – Categoría Teleconcepto.'),
  ('6.2.13', (select id from grupos_res1732 where numeral = '6.2'), 'Toma de muestras de cuello uterino', 'Servicio destinado a la realización de toma de muestras de tejido del cuello del útero, pruebas ADN/VPH, técnicas de inspección visual y muestras ginecológicas.', 'Complejidad: No aplica. Modalidades de prestación: Intramural, Extramural Jornada de Salud y Unidad Móvil.'),
  ('6.2.14', (select id from grupos_res1732 where numeral = '6.2'), 'Laboratorio de citologías', 'Servicio en el cual se realiza el análisis de las muestras de citología cervico-uterinas.', 'Complejidad: No aplica. Modalidades de prestación: Intramural; Telemedicina – Categoría Teleconcepto.'),
  ('6.2.15', (select id from grupos_res1732 where numeral = '6.2'), 'Laboratorio de histotecnología', 'Servicio donde se realizan los procedimientos técnicos para la preparación y montaje de tejidos y material citológico de origen humano.', 'Complejidad: No aplica. Modalidad de prestación: Intramural; Telemedicina – Categoría Teleconcepto.'),
  ('6.2.16', (select id from grupos_res1732 where numeral = '6.2'), 'Patología', 'Servicio donde se realiza el estudio integral de fragmentos de tejido u órganos (biopsias) y material citológico de origen humano.', 'Complejidad: Mediana. Modalidad de prestación: Intramural; Telemedicina – Categoría Teleconcepto.'),
  ('6.2.17', (select id from grupos_res1732 where numeral = '6.2'), 'Diálisis', 'Servicio donde se realizan las terapias de suplencia de la Insuficiencia Renal Crónica o Aguda, así como otras terapias extracorpóreas, dentro de las cuales se encuentran: Hemodiálisis y Diálisis peritoneal.', 'Complejidad: Hemodiálisis: Alta. Diálisis peritoneal: Mediana. Modalidades: Hemodiálisis - Intramural, Extramural Jornada de salud (solo para cuidado intensivo y hospitalización), Telemedicina – Categorías: Telexperticia, Teleconcepto, Teleconsulta. Diálisis peritoneal - Intramural, Telemedicina – Categorías: Telexperticia, Teleconcepto, Teleconsulta.'),
  ('6.3.1', (select id from grupos_res1732 where numeral = '6.3'), 'Hospitalización', 'Es el servicio que presta atención en salud a pacientes que por su condición de salud requieren estancia hospitalaria mayor a 24 horas para monitorización o realización de procedimientos. Cuando se realice trasplante de células progenitoras hematopoyéticas los autorizados son los que proceden de Médula Ósea, Sangre periférica o Sangre de cordón umbilical.', 'Complejidad: Baja, mediana y alta. Modalidades de prestación: Intramural, Extramural Domiciliaria (aplica únicamente para baja complejidad), Telemedicina – Categorías: Teleconcepto, Telemonitoreo.'),
  ('6.3.2', (select id from grupos_res1732 where numeral = '6.3'), 'Hospitalización paciente crónico', 'Es el servicio que presta atención en salud al paciente con patología crónica, con y sin ventilación, que requiere valoraciones y cuidados por personal de salud a través de un plan individualizado de atención, buscando mantener al paciente en su entorno, mantener funciones, prevenir el deterioro, con la máxima comodidad y alivio de síntomas, garantizando su seguridad. Será prestado con criterios controlados, con apoyo de profesionales, técnicos o auxiliares de salud y la participación de la familia o un cuidador.', 'Complejidad: Baja y mediana. Modalidades de prestación: Intramural, Extramural Domiciliaria, Telemedicina – Categorías: Teleconcepto, Telemonitoreo.'),
  ('6.3.3', (select id from grupos_res1732 where numeral = '6.3'), 'Cuidado básico neonatal', 'Es el servicio de atención del recién nacido hemodinámicamente estable, donde se realizan actividades para la atención integral de salud del paciente neonato (0-30 días de vida o 44 semanas de edad corregida).', 'Complejidad: Baja. Modalidad de prestación: Intramural; Telemedicina - Categoría: Teleconcepto.'),
  ('6.3.4', (select id from grupos_res1732 where numeral = '6.3'), 'Cuidado intermedio neonatal', 'Es el servicio donde se realizan actividades para la atención integral de la salud del neonato (0-30 días de vida o 44 semanas de edad corregida), que previsiblemente tienen un bajo riesgo de necesitar medidas terapéuticas de soporte vital, pero que cumplen con criterios médicos de ingreso al servicio.', 'Complejidad: Mediana. Modalidad de prestación: Intramural; Telemedicina – Categoría: Teleconcepto.'),
  ('6.3.5', (select id from grupos_res1732 where numeral = '6.3'), 'Cuidado intensivo neonatal', 'Servicio para la atención de pacientes recién nacidos críticamente enfermos, hasta los 30 días de vida o 44 semanas de edad corregida.', 'Complejidad: Alta. Modalidad de prestación: Intramural; Telemedicina – Categoría: Teleconcepto.'),
  ('6.3.6', (select id from grupos_res1732 where numeral = '6.3'), 'Cuidado intermedio pediátrico', 'Es el servicio para la atención de pacientes pediátricos con edades desde 1 mes o 44 semanas de edad corregida hasta los 18 años cumplidos de vida, o hasta la edad que por criterio médico pueden ser manejados en este servicio, que previsiblemente tienen un bajo riesgo de necesitar medidas terapéuticas de soporte vital.', 'Complejidad: Mediana. Modalidad de prestación: Intramural; Telemedicina – Categoría: Teleconcepto.'),
  ('6.3.7', (select id from grupos_res1732 where numeral = '6.3'), 'Cuidado intensivo pediátrico', 'Servicio para la atención de pacientes pediátricos (desde 1 mes o 44 semanas de edad corregida hasta los 18 años) cuya condición clínica pone en peligro la vida, con patologías que requieren soporte, monitorización y tratamiento especializado. Incluye la atención del paciente pediátrico quemado en condiciones críticas cuando se oferte en un ambiente exclusivo fuera del servicio.', 'Complejidad: Alta. Modalidad de prestación: Intramural; Telemedicina – Categoría: Teleconcepto.'),
  ('6.3.8', (select id from grupos_res1732 where numeral = '6.3'), 'Cuidado intermedio adulto', 'Es el servicio para la atención de pacientes adultos (o desde la edad que por criterio médico corresponda) que previsiblemente tienen un bajo riesgo de necesitar medidas terapéuticas de soporte vital, pero cuya condición requiere técnicas de monitoreo no invasivo, vigilancia y manejo especial, con cuidados de enfermería adicionales a los de hospitalización.', 'Complejidad: Mediana. Modalidad de prestación: Intramural; Telemedicina – Categorías: Teleconcepto.'),
  ('6.3.9', (select id from grupos_res1732 where numeral = '6.3'), 'Cuidado intensivo adultos', 'Servicio para la atención de pacientes adultos críticamente enfermos, con patologías que requieren soporte vital, monitorización y manejo especializado, cuya condición clínica pone en peligro la vida en forma inminente. Incluye la atención del paciente adulto quemado en condiciones críticas cuando se oferte en un ambiente exclusivo fuera del servicio.', 'Complejidad: Alta. Modalidad de prestación: Intramural; Telemedicina – Categoría: Teleconcepto.'),
  ('6.3.10', (select id from grupos_res1732 where numeral = '6.3'), 'Hospitalización en salud mental o consumo de sustancias psicoactivas', 'Es el servicio que presta atención hospitalaria a pacientes con alteraciones en salud mental o por consumo de sustancias psicoactivas, con una estancia mayor a 24 horas.', 'Complejidad: Mediana y alta. Modalidades de prestación: Intramural; Telemedicina – Categorías: Teleconcepto y Telexperticia.'),
  ('6.3.11', (select id from grupos_res1732 where numeral = '6.3'), 'Hospitalización parcial', 'Es el servicio que presta atención a pacientes en internación parcial, diurna, nocturna, fin de semana y otras que no impliquen estancia completa.', 'Complejidad: Mediana. Modalidades de prestación: Intramural, Telemedicina – Categorías: Teleconcepto, Telexperticia y Telemonitoreo.'),
  ('6.3.12', (select id from grupos_res1732 where numeral = '6.3'), 'Cuidado básico del consumo de sustancias psicoactivas', 'Es el servicio de internación en infraestructura no hospitalaria, para la atención de personas con consumo de sustancias psicoactivas, que incluye pernoctada.', 'Complejidad: Mediana. Modalidades de prestación: Intramural, Telemedicina – Categorías: teleconcepto y telexperticia.'),
  ('6.4.1', (select id from grupos_res1732 where numeral = '6.4'), 'Cirugía', 'Servicio destinado a la realización de procedimientos e intervenciones quirúrgicas, que requieren total asepsia. Los procedimientos e intervenciones pueden requerir o no internación para el manejo post operatorio. Cuando se realicen procedimientos de trasplante de órganos y tejidos, los autorizados son — Órganos: riñón, hígado, corazón, páncreas, pulmón, intestino, multivisceral y los demás que el Ministerio de Salud autorice; Tejidos: oculares, osteomuscular, cardiovascular, piel y componentes de la piel, y los demás que el Ministerio de Salud autorice.', 'Complejidades: Mediana y alta. Modalidades de prestación: Intramural, Extramural Jornada de Salud y Unidad Móvil (no aplica para trasplantes), Telemedicina – Categoría: Teleconcepto.'),
  ('6.5.1', (select id from grupos_res1732 where numeral = '6.5'), 'Urgencias', 'Servicio responsable de dar atención a las alteraciones de la integridad física, funcional y/o psíquica por cualquier causa, con diversos grados de severidad, que comprometen la vida o funcionalidad de la persona y que requiere de la prestación inmediata de servicios de salud, a fin de conservar la vida y prevenir consecuencias críticas presentes o futuras. El servicio debe ser prestado las 24 horas del día.', 'Complejidades: Baja, mediana y alta. Modalidad de prestación: Intramural; Telemedicina – Categorías: Teleconcepto, Telexperticia y Telemonitoreo.'),
  ('6.5.2', (select id from grupos_res1732 where numeral = '6.5'), 'Transporte asistencial', 'Es el servicio de salud donde se realiza el traslado y se brinda atención oportuna y permanente al paciente en ambulancias terrestres, marítimas, fluviales y aéreas.', 'Complejidad Baja: Transporte terrestre, marítimo y fluvial. Complejidad Mediana: Transporte terrestre, marítimo y fluvial. Complejidad Alta: Aéreo.'),
  ('6.5.3', (select id from grupos_res1732 where numeral = '6.5'), 'Atención prehospitalaria', 'Es el servicio de salud prestado en el sitio de ocurrencia del evento, responsable de las actividades, procedimientos e intervenciones terapéuticas prehospitalarias, encaminadas a prestar atención de urgencias a personas que han sufrido una alteración aguda de su integridad física o mental, causada por trauma o enfermedad, tendiente a preservar la vida y disminuir complicaciones y riesgos de invalidez y muerte, hasta la entrega del usuario al servicio de transporte asistencial. Puede incluir acciones de apoyo al salvamento y rescate.', 'Complejidad: Baja. Modalidades de prestación: Extramural; Telemedicina – Categoría: Telemonitoreo.'),
  ('6.5.4', (select id from grupos_res1732 where numeral = '6.5'), 'Atención del parto', 'Es el servicio destinado a la atención del preparto, parto y recuperación del binomio madre-hijo.', 'Complejidades: Baja, mediana y alta. Modalidades de prestación: Intramural; Telemedicina – Categorías: Telexperticia, Teleconcepto y Telemonitoreo.');
