insert into criterios_res3100 (llave, numero, item, pagina, criterio, grupo_res3100_id, servicio_res3100_id, numeral_grupo, numeral_servicio, estandar, complejidad, modalidad) values
  ('33.1;33.1. Número de exposiciones e imágenes tomadas que incluya el nombre del paciente y nombre del estudio realizado.', 872, '33.1', 108, '33.1. Número de exposiciones e imágenes tomadas que incluya el nombre del paciente y nombre del estudio realizado.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.1'), '11.3', '11.3.4.1', 'Estándar de Historia Clínica y Registros', 'baja, mediana y alta', 'intramural, telemedicina - prestador remisor'),
  ('33.2;33.2. Dosis de radiación expresadas en unidades según la tecnología del equipo.', 873, '33.2', 108, '33.2. Dosis de radiación expresadas en unidades según la tecnología del equipo.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.1'), '11.3', '11.3.4.1', 'Estándar de Historia Clínica y Registros', 'baja, mediana y alta', 'intramural, telemedicina - prestador remisor'),
  ('33.3;33.3. Número de imágenes rechazadas por el tecnólogo y el profesional de la medicina especialista en radiología e imágenes diagnósticas que incluya sus causas.', 874, '33.3', 108, '33.3. Número de imágenes rechazadas por el tecnólogo y el profesional de la medicina especialista en radiología e imágenes diagnósticas que incluya sus causas.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.1'), '11.3', '11.3.4.1', 'Estándar de Historia Clínica y Registros', 'baja, mediana y alta', 'intramural, telemedicina - prestador remisor'),
  ('33.4;33.4. Número de estudios repetidos y sus causas, cuando aplique.', 875, '33.4', 108, '33.4. Número de estudios repetidos y sus causas, cuando aplique.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.1'), '11.3', '11.3.4.1', 'Estándar de Historia Clínica y Registros', 'baja, mediana y alta', 'intramural, telemedicina - prestador remisor'),
  ('33.5;33.5. Control de calidad vigente, de los equipos generadores de radiación ionizante.', 876, '33.5', 108, '33.5. Control de calidad vigente, de los equipos generadores de radiación ionizante.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.1'), '11.3', '11.3.4.1', 'Estándar de Historia Clínica y Registros', 'baja, mediana y alta', 'intramural, telemedicina - prestador remisor'),
  ('34;34. Cumple con los criterios que le sean aplicables de todos los servicios y adicional a lo definido en la Modalidad intramural cuenta con los siguientes registros:
Verificación de la calidad de imagen para cada desplazamiento de la Unidad Móvil donde está ubicado el equipo generador de radiación ionizante, que incluye la toma de medidas correctivas, cuando aplique.', 877, '34', 108, '34. Cumple con los criterios que le sean aplicables de todos los servicios y adicional a lo definido en la Modalidad intramural cuenta con los siguientes registros:
Verificación de la calidad de imagen para cada desplazamiento de la Unidad Móvil donde está ubicado el equipo generador de radiación ionizante, que incluye la toma de medidas correctivas, cuando aplique.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.1'), '11.3', '11.3.4.1', 'Estándar de Historia Clínica y Registros', 'baja y mediana', 'extramural unidad móvil, telemedicina - prestador remisor'),
  ('35;35. Cumple con los criterios que le sean aplicables de todos los servicios.', 878, '35', 108, '35. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.1'), '11.3', '11.3.4.1', 'Estándar de Historia Clínica y Registros', 'baja, mediana y alta', 'telemedicina - prestador de referencia'),
  ('36;36. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente,', 879, '36', 109, '36. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente,', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.1'), '11.3', '11.3.4.1', 'Estándar de Interdependencia', 'baja', 'intramural'),
  ('37;37. Servicio de transporte asistencial cuando fuera de salas de cirugía se realicen procedimientos bajo sedación.', 880, '37', 109, '37. Servicio de transporte asistencial cuando fuera de salas de cirugía se realicen procedimientos bajo sedación.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.1'), '11.3', '11.3.4.1', 'Estándar de Interdependencia', 'baja', 'intramural'),
  ('38;38. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente,', 881, '38', 109, '38. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente,', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.1'), '11.3', '11.3.4.1', 'Estándar de Interdependencia', 'mediana y alta', 'intramural'),
  ('39;39. Cuando se realicen procedimientos con administración de medio de contraste e intervencionismo, disponibilidad de:
39.1 Servicio de urgencias.
39.2 Servicio de transporte asistencial.', 882, '39', 109, '39. Cuando se realicen procedimientos con administración de medio de contraste e intervencionismo, disponibilidad de:
39.1 Servicio de urgencias.
39.2 Servicio de transporte asistencial.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.1'), '11.3', '11.3.4.1', 'Estándar de Interdependencia', 'mediana y alta', 'intramural'),
  ('40;40. Cumple con los criterios que le sean aplicables de todos los servicios.', 883, '40', 109, '40. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.1'), '11.3', '11.3.4.1', 'Estándar de Interdependencia', 'baja, mediana y alta', 'extramural unidad móvil'),
  ('41;41. No aplica.', 884, '41', 109, '41. No aplica.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.1'), '11.3', '11.3.4.1', 'Estándar de Interdependencia', 'baja, mediana y alta', 'telemedicina – prestador remisor – prestador de referencia'),
  ('1;1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:', 885, '1', 110, '1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Talento Humano', 'mediana', 'intramural, extramural jornada de salud, unidad móvil y domiciliaria, telemedicina - prestador remisor'),
  ('1.1;1.1. Médico especializado en radiología e imágenes diagnósticas o aquellos médicos especialistas quienes en su pensum o formación académica hayan adquirido los conocimientos del manejo e interpretación del espectro electromagnético, del ultrasonido especialmente, así como de las radiaciones ionizantes para establecer el diagnóstico y/o el tratamiento de las enfermedades inherentes a sus especialidades. Para lo cual deberá acreditar el respectivo certificado.', 886, '1.1', 110, '1.1. Médico especializado en radiología e imágenes diagnósticas o aquellos médicos especialistas quienes en su pensum o formación académica hayan adquirido los conocimientos del manejo e interpretación del espectro electromagnético, del ultrasonido especialmente, así como de las radiaciones ionizantes para establecer el diagnóstico y/o el tratamiento de las enfermedades inherentes a sus especialidades. Para lo cual deberá acreditar el respectivo certificado.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Talento Humano', 'mediana', 'intramural, extramural jornada de salud, unidad móvil y domiciliaria, telemedicina - prestador remisor'),
  ('1.2;1.2. Cuando se realicen procedimientos de resonancia magnética cuenta con Técnico profesional o tecnólogo en imágenes diagnósticas, para la operación de equipos y adquisición de imágenes.', 887, '1.2', 110, '1.2. Cuando se realicen procedimientos de resonancia magnética cuenta con Técnico profesional o tecnólogo en imágenes diagnósticas, para la operación de equipos y adquisición de imágenes.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Talento Humano', 'mediana', 'intramural, extramural jornada de salud, unidad móvil y domiciliaria, telemedicina - prestador remisor'),
  ('2;2. Cumple con los criterios que le sean aplicables de todos los servicios.', 888, '2', 110, '2. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Talento Humano', 'mediana', 'telemedicina - prestador de referencia'),
  ('3;3. La interpretación de las imágenes diagnósticas es realizada médico especializado en radiología e imágenes diagnósticas o aquellos médicos especialistas quienes en su pensum o formación académica hayan adquirido los conocimientos del manejo e interpretación del espectro electromagnético, del ultrasonido especialmente, así como de las radiaciones ionizantes para establecer el diagnóstico y/o el tratamiento de las enfermedades inherentes a sus especialidades. Para lo cual deberá acreditar el respectivo certificado.', 889, '3', 110, '3. La interpretación de las imágenes diagnósticas es realizada médico especializado en radiología e imágenes diagnósticas o aquellos médicos especialistas quienes en su pensum o formación académica hayan adquirido los conocimientos del manejo e interpretación del espectro electromagnético, del ultrasonido especialmente, así como de las radiaciones ionizantes para establecer el diagnóstico y/o el tratamiento de las enfermedades inherentes a sus especialidades. Para lo cual deberá acreditar el respectivo certificado.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Talento Humano', 'mediana', 'telemedicina - prestador de referencia'),
  ('4;4. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con:
4.1 Ambiente exclusivo para el equipo generador de radiación no ionizante. La dimensión de este ambiente debe ser acorde al tipo de equipo generador de radiación no ionizante, su ficha técnica y a los procedimientos que se realicen, debe permitir movilización del talento humano, pacientes, usuarios y equipos biomédicos.
4.2 Unidad sanitaria, cuando el procedimiento lo requiera.', 890, '4', 110, '4. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con:
4.1 Ambiente exclusivo para el equipo generador de radiación no ionizante. La dimensión de este ambiente debe ser acorde al tipo de equipo generador de radiación no ionizante, su ficha técnica y a los procedimientos que se realicen, debe permitir movilización del talento humano, pacientes, usuarios y equipos biomédicos.
4.2 Unidad sanitaria, cuando el procedimiento lo requiera.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Infraestructura', 'mediana', 'intramural, extramural unidad móvil, telemedicina - prestador remisor'),
  ('5;5. Disponibilidad de:
5.1 Vestidor para pacientes y área para casilleros, cuando el procedimiento lo requiera.
5.2 Área para almacenamiento de dispositivos médicos e insumos.
5.3 Sala de espera.
5.4 Unidades sanitarias discriminadas por sexo.', 891, '5', 110, '5. Disponibilidad de:
5.1 Vestidor para pacientes y área para casilleros, cuando el procedimiento lo requiera.
5.2 Área para almacenamiento de dispositivos médicos e insumos.
5.3 Sala de espera.
5.4 Unidades sanitarias discriminadas por sexo.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Infraestructura', 'mediana', 'intramural, extramural unidad móvil, telemedicina - prestador remisor'),
  ('6;6. Cumple con los criterios que le sean aplicables de todos los servicios.', 892, '6', 110, '6. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Infraestructura', 'mediana', 'extramural jornada de salud, domiciliaria, telemedicina - prestador remisor'),
  ('7;7. Cumple con los criterios que le sean aplicables de todos los servicios.', 893, '7', 110, '7. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Infraestructura', 'mediana', 'telemedicina - prestador de referencia'),
  ('8;8. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente,
8.1 Cuenta con él o los equipos generadores de radiaciones no ionizantes, según los exámenes diagnósticos realizados.
8.2 Cuando se realice resonancia magnética y ultrasonido cuenta con pantalla o monitor grado médico.', 894, '8', 110, '8. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente,
8.1 Cuenta con él o los equipos generadores de radiaciones no ionizantes, según los exámenes diagnósticos realizados.
8.2 Cuando se realice resonancia magnética y ultrasonido cuenta con pantalla o monitor grado médico.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Dotación', 'mediana', 'intramural, telemedicina - prestador remisor'),
  ('9;9. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:
El o los equipos generadores de radiaciones no ionizantes, según los exámenes diagnósticos realizados, cuyas indicaciones del fabricante refieran que es un equipo portátil.', 895, '9', 110, '9. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:
El o los equipos generadores de radiaciones no ionizantes, según los exámenes diagnósticos realizados, cuyas indicaciones del fabricante refieran que es un equipo portátil.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Dotación', 'mediana', 'extramural unidad móvil, domiciliaria y jornada de salud, telemedicina - prestador remisor'),
  ('10;10. Cumple con los criterios que le sean aplicables de todos los servicios y los de la modalidad intramural y adicionalmente cuenta con equipo de captura y transmisión de datos e imágenes que asegure las condiciones de visualización de imagen y lectura.', 896, '10', 111, '10. Cumple con los criterios que le sean aplicables de todos los servicios y los de la modalidad intramural y adicionalmente cuenta con equipo de captura y transmisión de datos e imágenes que asegure las condiciones de visualización de imagen y lectura.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Dotación', 'mediana', 'telemedicina - prestador remisor'),
  ('11;11. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con pantalla o monitor grado médico.', 897, '11', 111, '11. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con pantalla o monitor grado médico.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Dotación', 'mediana', 'telemedicina - prestador de referencia'),
  ('12;12. Cumple con los criterios que le sean aplicables de todos los servicios.', 898, '12', 111, '12. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Medicamentos, Dispositivos Médicos e Insumos', 'mediana', 'intramural y extramural unidad móvil, domiciliaria y jornada de salud, telemedicina - prestador remisor – prestador de referencia'),
  ('13;13. Cumplen con los criterios definidos para todos los servicios y adicionalmente, cuenta con la siguiente información documentada:
13.1 Procedimientos para la realización de los exámenes diagnósticos.
13.2 Instrucciones a los pacientes sobre la preparación de los procedimientos diagnósticos, cuando se requiera.
13.3 Verificación de la calidad de imagen cuando aplique, que incluye la toma de medidas preventivas y correctivas.
13.4 Control de calidad del equipo cuando aplique, que incluye la toma de medidas correctivas.', 899, '13', 111, '13. Cumplen con los criterios definidos para todos los servicios y adicionalmente, cuenta con la siguiente información documentada:
13.1 Procedimientos para la realización de los exámenes diagnósticos.
13.2 Instrucciones a los pacientes sobre la preparación de los procedimientos diagnósticos, cuando se requiera.
13.3 Verificación de la calidad de imagen cuando aplique, que incluye la toma de medidas preventivas y correctivas.
13.4 Control de calidad del equipo cuando aplique, que incluye la toma de medidas correctivas.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Procesos Prioritarios', 'mediana', 'intramural, extramural unidad móvil, domiciliaria y jornada de salud, telemedicina - prestador remisor'),
  ('14;14. Cumple con los criterios que le sean aplicables de todos los servicios.', 900, '14', 111, '14. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Procesos Prioritarios', 'mediana', 'telemedicina - prestador de referencia'),
  ('15;15. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con registro de exámenes realizados.', 901, '15', 111, '15. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con registro de exámenes realizados.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Historia Clínica y Registros', 'mediana', 'intramural, extramural unidad móvil, domiciliaria y jornada de salud, telemedicina - prestador remisor'),
  ('16;16. Cumple con los criterios que le sean aplicables de todos los servicios.', 902, '16', 111, '16. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Historia Clínica y Registros', 'mediana', 'telemedicina - prestador de referencia'),
  ('17;17. No aplica', 903, '17', 111, '17. No aplica', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.4.2'), '11.3', '11.3.4.2', 'Estándar de Interdependencia', 'mediana', 'intramural, extramural unidad móvil, domiciliaria y jornada de salud, telemedicina - prestador remisor, prestador de referencia'),
  ('1;1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:', 904, '1', 112, '1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.5'), '11.3', '11.3.5', 'Estándar de Talento Humano', 'alta', 'intramural, telemedicina - prestador remisor'),
  ('1.1;1.1. Profesional de la enfermería, cuando en el servicio se administren terapias con radionúclidos con actividad mayor a 30 mCi, que cuenta con constancia de asistencia en las acciones de formación continua en protección radiológica, radiofarmacia y radiofármacos.', 905, '1.1', 112, '1.1. Profesional de la enfermería, cuando en el servicio se administren terapias con radionúclidos con actividad mayor a 30 mCi, que cuenta con constancia de asistencia en las acciones de formación continua en protección radiológica, radiofarmacia y radiofármacos.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.5'), '11.3', '11.3.5', 'Estándar de Talento Humano', 'alta', 'intramural, telemedicina - prestador remisor');
