insert into criterios_res3100 (llave, numero, item, pagina, criterio, grupo_res3100_id, servicio_res3100_id, numeral_grupo, numeral_servicio, estandar, complejidad, modalidad) values
  ('26.6;26.6. Instrumental básico estéril definido por el prestador de acuerdo con la oferta del servicio (adultos o pediatría), la capacidad instalada y los procedimientos documentados en el estándar de procesos prioritarios.', 550, '26.6', 82, '26.6. Instrumental básico estéril definido por el prestador de acuerdo con la oferta del servicio (adultos o pediatría), la capacidad instalada y los procedimientos documentados en el estándar de procesos prioritarios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Dotación', 'baja', 'extramural unidad móvil, jornada de salud y domiciliaria'),
  ('27;27. Cumple con los criterios que le sean aplicables de todos los servicios.', 551, '27', 82, '27. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Dotación', 'baja', 'extramural unidad móvil, jornada de salud y domiciliaria'),
  ('28;28. Cumple con los criterios que le sean aplicables de todos los servicios.', 552, '28', 83, '28. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Dotación', 'baja', 'telemedicina - Categoría interactiva y no interactiva – prestador de referencia'),
  ('29;29. Cumple con los criterios que le sean aplicables de todos los servicios y los establecidos en el servicio de consulta externa general.', 553, '29', 83, '29. Cumple con los criterios que le sean aplicables de todos los servicios y los establecidos en el servicio de consulta externa general.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Dotación', 'baja', 'telemedicina - Categoría telexperticia - prestador remisor'),
  ('30;30. Cumple con los criterios que le sean aplicables de todos los servicios.', 554, '30', 83, '30. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Dotación', 'baja', 'telemedicina - Categoría telexperticia - prestador de referencia'),
  ('31;31. Cumple con los criterios que le sean aplicables de todos los servicios.', 555, '31', 83, '31. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Dotación', 'baja', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('32;32. Cumple con los criterios que le sean aplicables de todos los servicios.', 556, '32', 83, '32. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Medicamentos, Dispositivos Médicos e Insumos', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('33;33. Cuando se oferte la estrategia para el manejo de la Enfermedad Respiratoria Aguda (ERA), el ambiente cuenta con oxígeno medicinal.', 557, '33', 83, '33. Cuando se oferte la estrategia para el manejo de la Enfermedad Respiratoria Aguda (ERA), el ambiente cuenta con oxígeno medicinal.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Medicamentos, Dispositivos Médicos e Insumos', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('34;34. Cumple con los criterios que le sean aplicables de todos los servicios.', 558, '34', 83, '34. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Medicamentos, Dispositivos Médicos e Insumos', 'baja', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('35;35. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuando se realicen procedimientos, cuenta con la siguiente información documentada:', 559, '35', 83, '35. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuando se realicen procedimientos, cuenta con la siguiente información documentada:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('35.1;35.1. Procedimientos que se pueden realizar, incluyendo aquellos que requieran anestesia local y no impliquen anestesia regional ni general.', 560, '35.1', 83, '35.1. Procedimientos que se pueden realizar, incluyendo aquellos que requieran anestesia local y no impliquen anestesia regional ni general.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('35.2;35.2. Información al paciente sobre:', 561, '35.2', 83, '35.2. Información al paciente sobre:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('35.2.1;35.2.1. Preparación.', 562, '35.2.1', 83, '35.2.1. Preparación.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('35.2.2;35.2.2. Recomendaciones post procedimiento.', 563, '35.2.2', 83, '35.2.2. Recomendaciones post procedimiento.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('35.2.3;35.2.3. Controles.', 564, '35.2.3', 83, '35.2.3. Controles.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('35.2.4;35.2.4. Posibles complicaciones.', 565, '35.2.4', 83, '35.2.4. Posibles complicaciones.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('36;36. La sala para el manejo de la Enfermedad Respiratoria Aguda (ERA), que dependa del servicio de consulta externa, debe estar señalizada y el prestador de servicios de salud cuenta con la siguiente información documentada:', 566, '36', 83, '36. La sala para el manejo de la Enfermedad Respiratoria Aguda (ERA), que dependa del servicio de consulta externa, debe estar señalizada y el prestador de servicios de salud cuenta con la siguiente información documentada:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('36.1;36.1. Manejo de pacientes con enfermedad respiratoria alta y baja, que incluya ingreso, valoración y seguimiento del estado clínico.', 567, '36.1', 83, '36.1. Manejo de pacientes con enfermedad respiratoria alta y baja, que incluya ingreso, valoración y seguimiento del estado clínico.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('36.2;36.2. Los tiempos máximos de manejo en la consulta externa, de los pacientes con enfermedad de vías respiratorias altas y bajas, y de remisión al servicio de hospitalización.', 568, '36.2', 83, '36.2. Los tiempos máximos de manejo en la consulta externa, de los pacientes con enfermedad de vías respiratorias altas y bajas, y de remisión al servicio de hospitalización.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('36.3;36.3. Las condiciones clínicas de los pacientes, que pueden ser manejadas en la sala y de las que no, de acuerdo con los procedimientos que se realicen.', 569, '36.3', 83, '36.3. Las condiciones clínicas de los pacientes, que pueden ser manejadas en la sala y de las que no, de acuerdo con los procedimientos que se realicen.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('37;37. Cumple con los criterios que le sean aplicables de todos los servicios.', 570, '37', 84, '37. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'telemedicina - Categoría interactiva y no interactiva – prestador de referencia'),
  ('38;38. Cumple con los criterios que le sean aplicables de todos los servicios y los establecidos en el servicio de consulta externa general.', 571, '38', 84, '38. Cumple con los criterios que le sean aplicables de todos los servicios y los establecidos en el servicio de consulta externa general.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'telemedicina - Categoría telexperticia - prestador remisor'),
  ('39;39. Cumple con los criterios que le sean aplicables de todos los servicios.', 572, '39', 84, '39. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'telemedicina - Categoría telexperticia - prestador de referencia'),
  ('40;40. Cumple con los criterios que le sean aplicables de todos los servicios', 573, '40', 84, '40. Cumple con los criterios que le sean aplicables de todos los servicios', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Procesos Prioritarios', 'baja', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('41;41. Cumple con los criterios que le sean aplicables de todos los servicios.', 574, '41', 84, '41. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Historia Clínica y Registros', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('42;42. Cumple con los criterios que le sean aplicables de todos los servicios.', 575, '42', 84, '42. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Historia Clínica y Registros', 'baja', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('43;43. Cumple con los criterios que le sean aplicables de todos los servicios.', 576, '43', 84, '43. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Interdependencia', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('44;44. No aplica.', 577, '44', 84, '44. No aplica.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Interdependencia', 'baja', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('1;1. Cumple con los criterios definidos para el servicio de consulta externa general y adicionalmente cuenta con:
1.1 <Aparte en rojo SUSPENDIDO provisionalmente> Profesional de la salud con título de especialista, según los programas académicos autorizados por el Ministerio de Educación Nacional.
Jurisprudencia Vigencia
1.2 Para medicina alternativa y terapias alternativas y complementarias, cuenta con profesional de la salud con título de especialista en el ámbito de su disciplina, para lo cual deberá acreditar la respectiva certificación académica de esa norma de competencia, expedida por una institución de educación superior legalmente reconocida por el Estado y de acuerdo con lo documentado por el prestador de servicios de salud en el estándar de procesos prioritarios.', 578, '1', 85, '1. Cumple con los criterios definidos para el servicio de consulta externa general y adicionalmente cuenta con:
1.1 <Aparte en rojo SUSPENDIDO provisionalmente> Profesional de la salud con título de especialista, según los programas académicos autorizados por el Ministerio de Educación Nacional.
Jurisprudencia Vigencia
1.2 Para medicina alternativa y terapias alternativas y complementarias, cuenta con profesional de la salud con título de especialista en el ámbito de su disciplina, para lo cual deberá acreditar la respectiva certificación académica de esa norma de competencia, expedida por una institución de educación superior legalmente reconocida por el Estado y de acuerdo con lo documentado por el prestador de servicios de salud en el estándar de procesos prioritarios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Talento Humano', 'mediana', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('2;2. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con:
Profesional de la salud con título de especialista de acuerdo con el servicio a ofertar.', 579, '2', 85, '2. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con:
Profesional de la salud con título de especialista de acuerdo con el servicio a ofertar.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Talento Humano', 'mediana', 'telemedicina - Categoría interactiva y no interactiva – prestador de referencia'),
  ('3;3. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente:', 580, '3', 85, '3. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Talento Humano', 'mediana', 'telemedicina - Categoría telexperticia - prestador remisor'),
  ('3.1;3.1. Cuando se realice telexperticia entre profesionales de la salud cuenta con el profesional de la salud con título de especialista de acuerdo con el servicio a ofertar.', 581, '3.1', 85, '3.1. Cuando se realice telexperticia entre profesionales de la salud cuenta con el profesional de la salud con título de especialista de acuerdo con el servicio a ofertar.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Talento Humano', 'mediana', 'telemedicina - Categoría telexperticia - prestador remisor'),
  ('3.2;3.2. Cuando realice telexperticia entre personal de salud no profesional y un profesional de la salud con título de especialista, el prestador remisor cuenta con técnico, tecnólogo o auxiliar que atiende presencialmente al usuario.', 582, '3.2', 85, '3.2. Cuando realice telexperticia entre personal de salud no profesional y un profesional de la salud con título de especialista, el prestador remisor cuenta con técnico, tecnólogo o auxiliar que atiende presencialmente al usuario.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Talento Humano', 'mediana', 'telemedicina - Categoría telexperticia - prestador remisor'),
  ('4;4. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con profesional de la salud con título de especialista que atiende a distancia, de acuerdo con el servicio a ofertar.', 583, '4', 85, '4. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con profesional de la salud con título de especialista que atiende a distancia, de acuerdo con el servicio a ofertar.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Talento Humano', 'mediana', 'telemedicina - Categoría telexperticia - prestador de referencia'),
  ('5;5. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con el personal de salud profesional con título de especialista que se requiera para realizar el telemonitoreo de acuerdo con lo documentado por el prestador de servicios de salud en el estándar de procesos prioritarios.', 584, '5', 85, '5. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con el personal de salud profesional con título de especialista que se requiera para realizar el telemonitoreo de acuerdo con lo documentado por el prestador de servicios de salud en el estándar de procesos prioritarios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Talento Humano', 'mediana', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('6;6. Cumple con los criterios definidos para el servicio de consulta externa general, de acuerdo con la oferta.', 585, '6', 85, '6. Cumple con los criterios definidos para el servicio de consulta externa general, de acuerdo con la oferta.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Infraestructura', 'mediana', 'intramural'),
  ('7;7. El consultorio de las especialidades de ginecoobstetricia y urología, cuentan con unidad sanitaria. Modalidades extramural unidad móvil, jornada de salud y domiciliaria', 586, '7', 85, '7. El consultorio de las especialidades de ginecoobstetricia y urología, cuentan con unidad sanitaria. Modalidades extramural unidad móvil, jornada de salud y domiciliaria', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Infraestructura', 'mediana', 'intramural'),
  ('8;8. Cumple con los criterios que le sean aplicables de todos los servicios.', 587, '8', 85, '8. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Infraestructura', 'mediana', 'intramural'),
  ('9;9. Cumple con los criterios que le sean aplicables de todos los servicios.', 588, '9', 85, '9. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Infraestructura', 'mediana', 'telemedicina - Categoría interactiva y no interactiva – prestador de referencia'),
  ('10;10. Cumple con los criterios establecidos en el servicio de consulta externa general.', 589, '10', 85, '10. Cumple con los criterios establecidos en el servicio de consulta externa general.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Infraestructura', 'mediana', 'telemedicina - Categoría telexperticia - prestador remisor');
