insert into criterios_res3100 (llave, numero, item, pagina, criterio, grupo_res3100_id, servicio_res3100_id, numeral_grupo, numeral_servicio, estandar, complejidad, modalidad) values
  ('3;3. Cuando en una edificación de uso exclusivo de salud funcione más de un prestador de servicios de salud con servicios de los grupos de consulta externa y apoyo diagnóstico y complementación terapéutica, cada prestador cuenta con infraestructura separada y delimitada físicamente. Se pueden compartir los siguientes ambientes y áreas: aseo, salas de espera y unidades sanitarias.', 27, '3', 61, '3. Cuando en una edificación de uso exclusivo de salud funcione más de un prestador de servicios de salud con servicios de los grupos de consulta externa y apoyo diagnóstico y complementación terapéutica, cada prestador cuenta con infraestructura separada y delimitada físicamente. Se pueden compartir los siguientes ambientes y áreas: aseo, salas de espera y unidades sanitarias.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('4;4. Las edificaciones donde se presten servicios de salud de urgencias y del grupo de internación, cuentan con tanque de almacenamiento de agua para el consumo humano que garantice como mínimo una reserva de 24 horas de servicio continuo, calculado con base en el consumo de 600 lt por cama/camilla día.', 28, '4', 61, '4. Las edificaciones donde se presten servicios de salud de urgencias y del grupo de internación, cuentan con tanque de almacenamiento de agua para el consumo humano que garantice como mínimo una reserva de 24 horas de servicio continuo, calculado con base en el consumo de 600 lt por cama/camilla día.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('5;5. Cuando el prestador de servicios de salud cuente con más de una infraestructura y estas se puedan vincular funcionalmente entre sí, lo harán mediante túnel o puente cubierto, o muro(s) colindante(s) que cuente(n) con acceso(s) que intercomunique(n) las infraestructuras, de uso exclusivo del prestador y adicionalmente cumplen con las siguientes características:', 29, '5', 61, '5. Cuando el prestador de servicios de salud cuente con más de una infraestructura y estas se puedan vincular funcionalmente entre sí, lo harán mediante túnel o puente cubierto, o muro(s) colindante(s) que cuente(n) con acceso(s) que intercomunique(n) las infraestructuras, de uso exclusivo del prestador y adicionalmente cumplen con las siguientes características:', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('5.1;5.1. Ancho que permita la movilización de camas, camillas, sillas de ruedas, equipos biomédicos y personal para el traslado de los pacientes en condiciones seguras.', 30, '5.1', 61, '5.1. Ancho que permita la movilización de camas, camillas, sillas de ruedas, equipos biomédicos y personal para el traslado de los pacientes en condiciones seguras.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('5.2;5.2. El piso del túnel o puente debe ser uniforme y de material antideslizante o con elementos que garanticen esta propiedad en todo su recorrido, con pasamanos a ambos lados y con protecciones laterales hacia espacios libres.', 31, '5.2', 61, '5.2. El piso del túnel o puente debe ser uniforme y de material antideslizante o con elementos que garanticen esta propiedad en todo su recorrido, con pasamanos a ambos lados y con protecciones laterales hacia espacios libres.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('5.3;5.3. Lo anterior siempre y cuando la norma urbanística de la jurisdicción donde se localizan las sedes haya aprobado esta forma de vinculación funcional entre las mismas.', 32, '5.3', 61, '5.3. Lo anterior siempre y cuando la norma urbanística de la jurisdicción donde se localizan las sedes haya aprobado esta forma de vinculación funcional entre las mismas.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('5.4;5.4. Esta edificación se podrá habilitar como una o varias sedes, de acuerdo con lo que determine el prestador de servicios de salud.
Lo anterior siempre y cuando la norma urbanística de la jurisdicción donde se localizan las sedes haya aprobado esta forma de vinculación funcional entre las mismas.', 33, '5.4', 61, '5.4. Esta edificación se podrá habilitar como una o varias sedes, de acuerdo con lo que determine el prestador de servicios de salud.
Lo anterior siempre y cuando la norma urbanística de la jurisdicción donde se localizan las sedes haya aprobado esta forma de vinculación funcional entre las mismas.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('6;Edificaciones de uso mixto
6. Cuando en una edificación de uso mixto funcione más de un prestador de servicios de salud, cada uno cuenta con infraestructura separada y delimitada físicamente. Se pueden compartir las salas de espera y las unidades sanitarias.', 34, '6', 61, 'Edificaciones de uso mixto
6. Cuando en una edificación de uso mixto funcione más de un prestador de servicios de salud, cada uno cuenta con infraestructura separada y delimitada físicamente. Se pueden compartir las salas de espera y las unidades sanitarias.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('7;7. En edificaciones de uso mixto pueden funcionar los prestadores de servicios de salud que oferten y presten servicios de los grupos de consulta externa, de apoyo diagnóstico y complementación terapéutica y los servicios del grupo quirúrgico que realicen exclusivamente procedimientos de cirugía ambulatoria.', 35, '7', 61, '7. En edificaciones de uso mixto pueden funcionar los prestadores de servicios de salud que oferten y presten servicios de los grupos de consulta externa, de apoyo diagnóstico y complementación terapéutica y los servicios del grupo quirúrgico que realicen exclusivamente procedimientos de cirugía ambulatoria.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('8;Edificaciones de uso exclusivo en salud y edificaciones de uso mixto
8. Los prestadores de servicios de salud ubicados en edificaciones de hasta tres (3) pisos o niveles contados a partir del nivel más bajo construido, y que funcionen en segundo o tercer nivel o piso, cuentan con ascensor o rampa o sistema alternativo de elevación. El sistema alternativo de elevación no puede ser utilizado cuando se presten servicios hospitalarios, cirugía, urgencias, o de atención del parto.', 36, '8', 61, 'Edificaciones de uso exclusivo en salud y edificaciones de uso mixto
8. Los prestadores de servicios de salud ubicados en edificaciones de hasta tres (3) pisos o niveles contados a partir del nivel más bajo construido, y que funcionen en segundo o tercer nivel o piso, cuentan con ascensor o rampa o sistema alternativo de elevación. El sistema alternativo de elevación no puede ser utilizado cuando se presten servicios hospitalarios, cirugía, urgencias, o de atención del parto.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('9;9. Los sistemas alternativos de elevación deben cumplir con las siguientes condiciones:', 37, '9', 62, '9. Los sistemas alternativos de elevación deben cumplir con las siguientes condiciones:', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('9.1;9.1. Su ubicación no interfiera con el acceso y evacuación de los usuarios por las escaleras.', 38, '9.1', 62, '9.1. Su ubicación no interfiera con el acceso y evacuación de los usuarios por las escaleras.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('9.2;9.2. Estén disponibles tanto para el acceso como para la evacuación de los usuarios.', 39, '9.2', 62, '9.2. Estén disponibles tanto para el acceso como para la evacuación de los usuarios.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('9.3;9.3. Su manejo sea autónomo.', 40, '9.3', 62, '9.3. Su manejo sea autónomo.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('9.4;9.4. Garanticen seguridad durante su uso.', 41, '9.4', 62, '9.4. Garanticen seguridad durante su uso.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('10;10. Las edificaciones con más de tres (3) pisos o niveles, contados a partir del nivel más bajo construido, cuentan con ascensor.', 42, '10', 62, '10. Las edificaciones con más de tres (3) pisos o niveles, contados a partir del nivel más bajo construido, cuentan con ascensor.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('11;11. En edificaciones donde se presten servicios de los grupos de internación, atención del parto, quirúrgicos o urgencias para la movilización de pacientes en camilla, la cabina de los ascensores debe tener las dimensiones interiores mínimas de 2.20 de profundidad y de 1.20 de ancho, que garantice el traslado seguro de los pacientes. Las dimensiones de la cabina podrán ser variables en el o los ascensores que el prestador determine para la movilización de usuarios a pie o en sillas de ruedas.', 43, '11', 62, '11. En edificaciones donde se presten servicios de los grupos de internación, atención del parto, quirúrgicos o urgencias para la movilización de pacientes en camilla, la cabina de los ascensores debe tener las dimensiones interiores mínimas de 2.20 de profundidad y de 1.20 de ancho, que garantice el traslado seguro de los pacientes. Las dimensiones de la cabina podrán ser variables en el o los ascensores que el prestador determine para la movilización de usuarios a pie o en sillas de ruedas.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('12;12. Si se tienen escaleras o rampas, el piso debe ser uniforme y de material antideslizante o con elementos que garanticen esta propiedad en todo su recorrido, con pasamanos a uno o ambos lados y con protecciones laterales hacia espacios libres.', 44, '12', 62, '12. Si se tienen escaleras o rampas, el piso debe ser uniforme y de material antideslizante o con elementos que garanticen esta propiedad en todo su recorrido, con pasamanos a uno o ambos lados y con protecciones laterales hacia espacios libres.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('13;13. Las edificaciones donde se presten servicios de salud cuentan con suministro de agua, energía eléctrica, conexión a la red de alcantarillado y sistemas de comunicaciones.', 45, '13', 62, '13. Las edificaciones donde se presten servicios de salud cuentan con suministro de agua, energía eléctrica, conexión a la red de alcantarillado y sistemas de comunicaciones.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('14;14. En edificaciones donde se presten servicios de cirugía, atención del parto, laboratorio clínico, urgencias, gestión pre transfusional, diálisis, hospitalarios, imágenes diagnósticas, vacunación, servicio farmacéutico y los que requieran cadena de frio, cuentan con planta eléctrica.', 46, '14', 62, '14. En edificaciones donde se presten servicios de cirugía, atención del parto, laboratorio clínico, urgencias, gestión pre transfusional, diálisis, hospitalarios, imágenes diagnósticas, vacunación, servicio farmacéutico y los que requieran cadena de frio, cuentan con planta eléctrica.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('15;15. El prestador de servicios de salud que utilice equipos generadores de radiaciones ionizantes, cuenta con licencia de práctica médica vigente expedida por la entidad competente.', 47, '15', 62, '15. El prestador de servicios de salud que utilice equipos generadores de radiaciones ionizantes, cuenta con licencia de práctica médica vigente expedida por la entidad competente.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('16;16. El prestador de servicios de salud que utilice fuentes radioactivas cuenta con autorización vigente de empleo de material radiactivo, expedida por la entidad reguladora competente.', 48, '16', 62, '16. El prestador de servicios de salud que utilice fuentes radioactivas cuenta con autorización vigente de empleo de material radiactivo, expedida por la entidad reguladora competente.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('17;17. Cada prestador de servicios de salud debe contar con el respectivo concepto sanitario que dé cumplimiento a lo establecido en la normatividad sanitaria vigente en aspectos tales como agua para consumo humano, gestión de residuos, control de vectores, orden y aseo, condiciones locativas, entre otros. Este concepto será emitido por las autoridades sanitarias correspondientes, en el marco de sus competencias, y debe considerar los servicios de apoyo como lavandería y servicio de alimentación.
Cuando estos servicios de apoyo son contratados con terceros, dichos proveedores deben contar con el concepto sanitario correspondiente a la actividad de bienes y servicios que presta.', 49, '17', 63, '17. Cada prestador de servicios de salud debe contar con el respectivo concepto sanitario que dé cumplimiento a lo establecido en la normatividad sanitaria vigente en aspectos tales como agua para consumo humano, gestión de residuos, control de vectores, orden y aseo, condiciones locativas, entre otros. Este concepto será emitido por las autoridades sanitarias correspondientes, en el marco de sus competencias, y debe considerar los servicios de apoyo como lavandería y servicio de alimentación.
Cuando estos servicios de apoyo son contratados con terceros, dichos proveedores deben contar con el concepto sanitario correspondiente a la actividad de bienes y servicios que presta.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('18;Generalidades de los ambientes y las áreas de los servicios y sus características
18. Las áreas y ambientes de todos los servicios de salud cuentan con ventilación e iluminación natural o artificial.', 50, '18', 63, 'Generalidades de los ambientes y las áreas de los servicios y sus características
18. Las áreas y ambientes de todos los servicios de salud cuentan con ventilación e iluminación natural o artificial.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('19;19. Las áreas de circulación de los servicios están libres de obstáculos de manera que permitan la movilización de pacientes, talento humano, usuarios y equipos biomédicos.', 51, '19', 63, '19. Las áreas de circulación de los servicios están libres de obstáculos de manera que permitan la movilización de pacientes, talento humano, usuarios y equipos biomédicos.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('20;20. Los ambientes y áreas que hagan parte de cualquier servicio de salud, deben permitir la instalación y movilización de equipos biomédicos y personal necesarios para la atención del paciente en condiciones de rutina o de emergencia.', 52, '20', 63, '20. Los ambientes y áreas que hagan parte de cualquier servicio de salud, deben permitir la instalación y movilización de equipos biomédicos y personal necesarios para la atención del paciente en condiciones de rutina o de emergencia.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('21;21. En los servicios del grupo quirúrgico, los ambientes y áreas clasificados como no restringidos, semi-restringidos y restringidos, deben señalizarse mediante la demarcación permanente en piso con material lavable y resistente al tráfico pesado, utilizando los siguientes colores:', 53, '21', 63, '21. En los servicios del grupo quirúrgico, los ambientes y áreas clasificados como no restringidos, semi-restringidos y restringidos, deben señalizarse mediante la demarcación permanente en piso con material lavable y resistente al tráfico pesado, utilizando los siguientes colores:', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('21.1;21.1. Verde: Ambientes o áreas no restringidas', 54, '21.1', 63, '21.1. Verde: Ambientes o áreas no restringidas', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('21.2;21.2. Amarillo: Ambientes o áreas semi-restringidas', 55, '21.2', 63, '21.2. Amarillo: Ambientes o áreas semi-restringidas', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('21.3;21.3. Roja: Ambientes o áreas restringidas', 56, '21.3', 63, '21.3. Roja: Ambientes o áreas restringidas', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('22;22. Cada uno de los pisos o niveles de la edificación cuenta con señalización y planos indicativos de las rutas de evacuación, salidas de emergencia y puntos de encuentro, visible al público en general.', 57, '22', 63, '22. Cada uno de los pisos o niveles de la edificación cuenta con señalización y planos indicativos de las rutas de evacuación, salidas de emergencia y puntos de encuentro, visible al público en general.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas'),
  ('23;23. Si el prestador de servicios de salud no tiene habilitado el servicio de gestión pre transfusional, pero realiza procedimientos de transfusión sanguínea en alguno de sus servicios habilitados, tiene disponibilidad de un área con iluminación y ventilación natural o artificial, para la ubicación de la dotación requerida de acuerdo con los componentes sanguíneos a transfundir.', 58, '23', 63, '23. Si el prestador de servicios de salud no tiene habilitado el servicio de gestión pre transfusional, pero realiza procedimientos de transfusión sanguínea en alguno de sus servicios habilitados, tiene disponibilidad de un área con iluminación y ventilación natural o artificial, para la ubicación de la dotación requerida de acuerdo con los componentes sanguíneos a transfundir.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.2', 'Estándar de Infraestructura', 'Todas', 'Todas');
