insert into criterios_res3100 (llave, numero, item, pagina, criterio, grupo_res3100_id, servicio_res3100_id, numeral_grupo, numeral_servicio, estandar, complejidad, modalidad) values
  ('28;28. Cumple con los criterios que le sean aplicables de todos los servicios.', 713, '28', 96, '28. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.1'), '11.3', '11.3.1', 'Estándar de Historia Clínica y Registros', 'Todas', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('29;29. No aplica', 714, '29', 96, '29. No aplica', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.1'), '11.3', '11.3.1', 'Estándar de Interdependencia', 'Todas', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('30;30. No aplica.', 715, '30', 96, '30. No aplica.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.1'), '11.3', '11.3.1', 'Estándar de Interdependencia', 'Todas', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('1;1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente:
Cumple con lo definido en el Decreto 2200 de 2005, compilado en el Decreto 780 de 2016 (Art 2.5.3.10.9), y la Resolución 1403 de 2007 (Manual de condiciones esenciales y procedimientos del servicio farmacéutico Título I Capítulo II Numerales 3.2, 3.2.1; 3.2.2 y Capítulo III Numeral 1.2), o las normas que los modifiquen, adicionen o sustituyan.', 716, '1', 97, '1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente:
Cumple con lo definido en el Decreto 2200 de 2005, compilado en el Decreto 780 de 2016 (Art 2.5.3.10.9), y la Resolución 1403 de 2007 (Manual de condiciones esenciales y procedimientos del servicio farmacéutico Título I Capítulo II Numerales 3.2, 3.2.1; 3.2.2 y Capítulo III Numeral 1.2), o las normas que los modifiquen, adicionen o sustituyan.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Talento Humano', 'Todas', 'intramural y extramural domiciliaria'),
  ('2;2. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con lo definido con el numeral 1 del servicio farmacéutico.', 717, '2', 97, '2. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con lo definido con el numeral 1 del servicio farmacéutico.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Talento Humano', 'Todas', 'telemedicina - Categoría telexperticia – prestador remisor – prestador de referencia'),
  ('3;3. El talento humano brinda en esta modalidad lo relacionado con la atención farmacéutica a los pacientes que lo requieran, a través de telemedicina – categorías interactiva y no interactiva, telexperticia sincrónico y asincrónico.
El apoyo a distancia del profesional Químico Farmacéutico no reemplaza el contar con el talento humano definido en el servicio.', 718, '3', 97, '3. El talento humano brinda en esta modalidad lo relacionado con la atención farmacéutica a los pacientes que lo requieran, a través de telemedicina – categorías interactiva y no interactiva, telexperticia sincrónico y asincrónico.
El apoyo a distancia del profesional Químico Farmacéutico no reemplaza el contar con el talento humano definido en el servicio.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Talento Humano', 'Todas', 'telemedicina - Categoría telexperticia – prestador remisor – prestador de referencia'),
  ('4;4. Cumple con los criterios que le sean aplicables de todos los servicios.', 719, '4', 97, '4. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Infraestructura', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('5;5. Cuenta con:', 720, '5', 97, '5. Cuenta con:', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Infraestructura', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('5.1;5.1. Ambiente o área administrativa.', 721, '5.1', 97, '5.1. Ambiente o área administrativa.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Infraestructura', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('5.2;5.2. Ambiente o área de recepción de medicamentos y dispositivos médicos.', 722, '5.2', 97, '5.2. Ambiente o área de recepción de medicamentos y dispositivos médicos.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Infraestructura', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('5.3;5.3. Ambiente o área de dispensación de medicamentos y entrega de dispositivos médicos.', 723, '5.3', 97, '5.3. Ambiente o área de dispensación de medicamentos y entrega de dispositivos médicos.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Infraestructura', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('5.4;5.4. Ambiente o área de almacenamiento, que garantice las condiciones temperatura y humedad recomendadas por el fabricante. Incluye cadena de frio, cuando aplique.', 724, '5.4', 97, '5.4. Ambiente o área de almacenamiento, que garantice las condiciones temperatura y humedad recomendadas por el fabricante. Incluye cadena de frio, cuando aplique.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Infraestructura', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('5.5;5.5. Ambiente o área independiente de medicamentos de control especial cuando aplique, que garantice las condiciones temperatura y humedad recomendadas por el fabricante.', 725, '5.5', 97, '5.5. Ambiente o área independiente de medicamentos de control especial cuando aplique, que garantice las condiciones temperatura y humedad recomendadas por el fabricante.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Infraestructura', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('5.6;5.6. Ambiente o área para almacenamiento de productos rechazados, devueltos y retirados.', 726, '5.6', 97, '5.6. Ambiente o área para almacenamiento de productos rechazados, devueltos y retirados.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Infraestructura', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('5.7;5.7. Ambiente o área para almacenamiento de productos destruidos o desnaturalizados por vencimiento o deterioro.', 727, '5.7', 97, '5.7. Ambiente o área para almacenamiento de productos destruidos o desnaturalizados por vencimiento o deterioro.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Infraestructura', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('5.8;5.8. Ambiente o área de cuarentena de medicamentos.', 728, '5.8', 97, '5.8. Ambiente o área de cuarentena de medicamentos.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Infraestructura', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('6;6. Cumple con los criterios que le sean aplicables de todos los servicios.', 729, '6', 97, '6. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Infraestructura', 'baja', 'telemedicina - Categoría telexperticia – prestador de referencia'),
  ('7;7. Cumple con los criterios definidos para el servicio farmacéutico de baja complejidad y adicionalmente cumple con lo definido en el Manual que adopta la Resolución 1403 de 2007, en el Título I Capítulo II numeral 1.2.2 y Título I Capítulo III numeral 1, o las normas que los modifiquen, adicionen o sustituyan.', 730, '7', 98, '7. Cumple con los criterios definidos para el servicio farmacéutico de baja complejidad y adicionalmente cumple con lo definido en el Manual que adopta la Resolución 1403 de 2007, en el Título I Capítulo II numeral 1.2.2 y Título I Capítulo III numeral 1, o las normas que los modifiquen, adicionen o sustituyan.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Infraestructura', 'mediana y alta', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('8;8. Cumple con los criterios que le sean aplicables de todos los servicios.', 731, '8', 98, '8. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Infraestructura', 'mediana y alta', 'telemedicina - Categoría telexperticia – prestador de referencia'),
  ('9;9. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:', 732, '9', 98, '9. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Dotación', 'baja, mediana y alta', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('9.1;9.1. La dotación y mobiliario exclusivos y necesarios para el cumplimiento de los objetivos de los procesos generales y especiales que brinda el servicio, de acuerdo con las recomendaciones dadas por los fabricantes.', 733, '9.1', 98, '9.1. La dotación y mobiliario exclusivos y necesarios para el cumplimiento de los objetivos de los procesos generales y especiales que brinda el servicio, de acuerdo con las recomendaciones dadas por los fabricantes.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Dotación', 'baja, mediana y alta', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('9.2;9.2. Instrumentos para medir la humedad relativa y la temperatura, en donde se almacenen medicamentos y dispositivos médicos.', 734, '9.2', 98, '9.2. Instrumentos para medir la humedad relativa y la temperatura, en donde se almacenen medicamentos y dispositivos médicos.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Dotación', 'baja, mediana y alta', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('10;10. Cumple con los criterios que le sean aplicables de todos los servicios.', 735, '10', 98, '10. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Dotación', 'baja, mediana y alta', 'telemedicina - Categoría telexperticia – prestador de referencia'),
  ('11;11. Cumple con los criterios que le sean aplicables de todos los servicios.', 736, '11', 98, '11. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Medicamentos, Dispositivos Médicos e Insumos', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('12;12. Cumple con los criterios que le sean aplicables de todos los servicios.', 737, '12', 99, '12. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Medicamentos, Dispositivos Médicos e Insumos', 'baja', 'telemedicina - Categoría telexperticia – prestador de referencia'),
  ('13;13. Cumple con los criterios definidos para el servicio farmacéutico de baja complejidad y adicionalmente cuenta con:
Certificación en buenas prácticas de elaboración vigente, expedida por el Invima para los procesos especiales que se realicen en la central de mezclas ya sea propia o contratada.', 738, '13', 99, '13. Cumple con los criterios definidos para el servicio farmacéutico de baja complejidad y adicionalmente cuenta con:
Certificación en buenas prácticas de elaboración vigente, expedida por el Invima para los procesos especiales que se realicen en la central de mezclas ya sea propia o contratada.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Medicamentos, Dispositivos Médicos e Insumos', 'mediana y alta', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia – prestador remisor'),
  ('14;14. Cumple con los criterios que le sean aplicables de todos los servicios.', 739, '14', 99, '14. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Medicamentos, Dispositivos Médicos e Insumos', 'mediana y alta', 'telemedicina - Categoría telexperticia – prestador de referencia'),
  ('15;15. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con la siguiente información documentada:', 740, '15', 99, '15. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con la siguiente información documentada:', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia - prestador remisor'),
  ('15.1;15.1. Procesos generales que realice, elaborado por el responsable del servicio.', 741, '15.1', 99, '15.1. Procesos generales que realice, elaborado por el responsable del servicio.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia - prestador remisor'),
  ('15.2;15.2. Información visible al usuario que prohíba la asesoría farmacológica, por parte de personal diferente al profesional químico farmacéutico o al Profesional en Medicina tratante.', 742, '15.2', 99, '15.2. Información visible al usuario que prohíba la asesoría farmacológica, por parte de personal diferente al profesional químico farmacéutico o al Profesional en Medicina tratante.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia - prestador remisor'),
  ('15.3;15.3. Manejo de medicamentos de control especial cuando lo realice.', 743, '15.3', 99, '15.3. Manejo de medicamentos de control especial cuando lo realice.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia - prestador remisor'),
  ('15.4;15.4. Seguimiento a condiciones ambientales de temperatura y humedad.', 744, '15.4', 99, '15.4. Seguimiento a condiciones ambientales de temperatura y humedad.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Procesos Prioritarios', 'baja', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia - prestador remisor'),
  ('16;16. Cumple con los criterios que le sean aplicables de todos los servicios.', 745, '16', 99, '16. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Procesos Prioritarios', 'baja', 'telemedicina - Categoría telexperticia – prestador de referencia'),
  ('17;17. Cumple con los criterios definidos para el servicio farmacéutico en baja complejidad y adicionalmente, cuenta con información documentada de cada uno de los procesos especiales que se realicen en el servicio.', 746, '17', 99, '17. Cumple con los criterios definidos para el servicio farmacéutico en baja complejidad y adicionalmente, cuenta con información documentada de cada uno de los procesos especiales que se realicen en el servicio.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Procesos Prioritarios', 'mediana y alta', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia - prestador remisor'),
  ('18;18. Cumple con los criterios que le sean aplicables de todos los servicios.', 747, '18', 100, '18. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Procesos Prioritarios', 'mediana y alta', 'telemedicina - Categoría telexperticia – prestador de referencia'),
  ('19;19. Cumple con los criterios que le sean aplicables de todos los servicios.', 748, '19', 100, '19. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Historia Clínica y Registros', 'baja, mediana y alta', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia - prestador remisor'),
  ('20;20. Cumple con los criterios que le sean aplicables de todos los servicios.', 749, '20', 100, '20. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Historia Clínica y Registros', 'baja, mediana y alta', 'telemedicina - Categoría telexperticia – prestador de referencia'),
  ('21;21. No aplica.', 750, '21', 100, '21. No aplica.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Interdependencia', 'baja, mediana y alta', 'intramural, extramural domiciliaria, telemedicina categoría telexperticia - prestador remisor'),
  ('22;22. No aplica.', 751, '22', 100, '22. No aplica.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.2'), '11.3', '11.3.2', 'Estándar de Interdependencia', 'baja, mediana y alta', 'telemedicina - Categoría telexperticia – prestador de referencia'),
  ('1;1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con:
Profesional de odontología o tecnólogo en radiología e imágenes diagnósticas, o técnico profesional o auxiliar de odontología o auxiliar en salud oral o auxiliar de higiene oral.', 752, '1', 101, '1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con:
Profesional de odontología o tecnólogo en radiología e imágenes diagnósticas, o técnico profesional o auxiliar de odontología o auxiliar en salud oral o auxiliar de higiene oral.', (select id from grupos_res3100 where numeral = '11.3'), (select id from servicios_res3100 where numeral = '11.3.3'), '11.3', '11.3.3', 'Estándar de Talento Humano', 'Todas', 'intramural y extramural unidad móvil');
