insert into criterios_res3100 (llave, numero, item, pagina, criterio, grupo_res3100_id, servicio_res3100_id, numeral_grupo, numeral_servicio, estandar, complejidad, modalidad) values
  ('4.5;4.5.2 Unidades sanitarias discriminadas por sexo.', 634, '4.5', 88, '4.5.2 Unidades sanitarias discriminadas por sexo.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('5;5. Adicional a los criterios definidos para todos los servicios, la sede del prestador de servicios de salud que habilite el servicio de vacunación cuenta con:
5.1 Ambiente para el alistamiento de termos y cajas térmicas.
5.2 Ambiente de cadena de frío, que puede ser el mismo de la modalidad intramural, que incluye un mesón con poceta, con capacidad para el lavado de los termos, con grifo cuello de cisne o ducha teléfono.
5.3 Área para el almacenamiento de dispositivos médicos e insumos, que puede estar ubicado en otro ambiente diferente al consultorio.
5.4 Lavamanos.', 635, '5', 89, '5. Adicional a los criterios definidos para todos los servicios, la sede del prestador de servicios de salud que habilite el servicio de vacunación cuenta con:
5.1 Ambiente para el alistamiento de termos y cajas térmicas.
5.2 Ambiente de cadena de frío, que puede ser el mismo de la modalidad intramural, que incluye un mesón con poceta, con capacidad para el lavado de los termos, con grifo cuello de cisne o ducha teléfono.
5.3 Área para el almacenamiento de dispositivos médicos e insumos, que puede estar ubicado en otro ambiente diferente al consultorio.
5.4 Lavamanos.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'extramural unidad móvil, jornada de salud y domiciliaria'),
  ('6;6. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con:
6.1 Refrigerador precalificado por la Organización Mundial de la Salud para almacenamiento de vacunas.
6.2 Para los refrigeradores con alimentación eléctrica cuenta con regulador o estabilizador electrónico de voltaje independiente, o conexión a una fuente regulada con indicador de polo a tierra.
6.3 Papelería, cajas de transporte y termos portavacunas precalificados por la Organización Mundial de la Salud para manejo de vacunas; y los demás insumos necesarios para la prestación del servicio.', 636, '6', 89, '6. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con:
6.1 Refrigerador precalificado por la Organización Mundial de la Salud para almacenamiento de vacunas.
6.2 Para los refrigeradores con alimentación eléctrica cuenta con regulador o estabilizador electrónico de voltaje independiente, o conexión a una fuente regulada con indicador de polo a tierra.
6.3 Papelería, cajas de transporte y termos portavacunas precalificados por la Organización Mundial de la Salud para manejo de vacunas; y los demás insumos necesarios para la prestación del servicio.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Dotación', 'baja', 'intramural'),
  ('7;7. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:
7.1 Congelador con la capacidad suficiente para almacenar los paquetes fríos necesarios para el alistamiento de la totalidad de las cajas térmicas y termos.
7.2 Refrigerador precalificado por la Organización Mundial de la Salud para almacenamiento de vacunas.
7.3 Caja térmica o termo porta vacunas precalificados por la Organización Mundial de la Salud, para el traslado de los biológicos.', 637, '7', 89, '7. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:
7.1 Congelador con la capacidad suficiente para almacenar los paquetes fríos necesarios para el alistamiento de la totalidad de las cajas térmicas y termos.
7.2 Refrigerador precalificado por la Organización Mundial de la Salud para almacenamiento de vacunas.
7.3 Caja térmica o termo porta vacunas precalificados por la Organización Mundial de la Salud, para el traslado de los biológicos.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Dotación', 'baja', 'extramural unidad móvil, jornada de salud y domiciliaria'),
  ('8;8. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:
Si se presenta interrupción de la cadena de frío, el prestador de servicios de salud realiza notificación según el procedimiento establecido por el Invima.', 638, '8', 89, '8. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:
Si se presenta interrupción de la cadena de frío, el prestador de servicios de salud realiza notificación según el procedimiento establecido por el Invima.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Medicamentos, Dispositivos Médicos e Insumos', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('9;9. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con la siguiente información documentada:
9.1 Vacunación segura.
9.2 Reporte y manejo de Eventos Supuestamente Adversos Atribuidos a la Vacunación o Inmunización -ESAVI (medición, análisis, reporte, gestión y monitoreo).
9.3 Vigilancia de inmunoprevenibles.
9.4 Seguimiento al sistema de información del Programa Ampliado de Inmunizaciones -PAI y seguimiento a cohortes.
9.5 Protocolo para la inmunización en casos de urgencia o para víctimas de violencia sexual por medio de la respuesta en red.
9.6 Vacunación sin barreras.', 639, '9', 90, '9. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con la siguiente información documentada:
9.1 Vacunación segura.
9.2 Reporte y manejo de Eventos Supuestamente Adversos Atribuidos a la Vacunación o Inmunización -ESAVI (medición, análisis, reporte, gestión y monitoreo).
9.3 Vigilancia de inmunoprevenibles.
9.4 Seguimiento al sistema de información del Programa Ampliado de Inmunizaciones -PAI y seguimiento a cohortes.
9.5 Protocolo para la inmunización en casos de urgencia o para víctimas de violencia sexual por medio de la respuesta en red.
9.6 Vacunación sin barreras.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Procesos Prioritarios', 'baja', 'intramural'),
  ('10;10. Cumple con los criterios que le sean aplicables de todos los servicios, la modalidad intramural y adicionalmente cuenta con:
Si el prestador de servicios de salud administra la vacuna en un ambiente diferente al consultorio de vacunación cuenta con información documentada para el alistamiento de los biológicos para uso diario, así como la conservación de la cadena de frio.', 640, '10', 90, '10. Cumple con los criterios que le sean aplicables de todos los servicios, la modalidad intramural y adicionalmente cuenta con:
Si el prestador de servicios de salud administra la vacuna en un ambiente diferente al consultorio de vacunación cuenta con información documentada para el alistamiento de los biológicos para uso diario, así como la conservación de la cadena de frio.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Procesos Prioritarios', 'baja', 'extramural unidad móvil, jornada de salud y domiciliaria'),
  ('11;11. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:
11.1 Instrumentos de registros establecidos para el PAI bajo los lineamientos del Ministerio de Salud y Protección Social.
11.2 Registro nominal de la información del PAI, durante la atención.
11.3 Registro del carné de vacunación definido por el Ministerio de Salud y Protección Social en forma clara, legible, sin tachones, enmendaduras y sin dejar espacios en blanco.', 641, '11', 90, '11. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:
11.1 Instrumentos de registros establecidos para el PAI bajo los lineamientos del Ministerio de Salud y Protección Social.
11.2 Registro nominal de la información del PAI, durante la atención.
11.3 Registro del carné de vacunación definido por el Ministerio de Salud y Protección Social en forma clara, legible, sin tachones, enmendaduras y sin dejar espacios en blanco.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Historia Clínica y Registros', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('12;12. No aplica.', 642, '12', 90, '12. No aplica.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Interdependencia', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('1;1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:', 643, '1', 91, '1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Talento Humano', 'mediana', 'intramural, extramural unidad móvil y jornada de salud'),
  ('1.1;1.1. Profesional de la medicina especialista en medicina del trabajo o medicina laboral o seguridad y salud en el trabajo con licencia vigente de seguridad y salud en el trabajo expedida por autoridad competente.', 644, '1.1', 91, '1.1. Profesional de la medicina especialista en medicina del trabajo o medicina laboral o seguridad y salud en el trabajo con licencia vigente de seguridad y salud en el trabajo expedida por autoridad competente.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Talento Humano', 'mediana', 'intramural, extramural unidad móvil y jornada de salud'),
  ('1.2;1.2. Cuando se realicen pruebas complementarias de tamización (audiometría, visiometría, espirometría según aplique), disponibilidad de profesionales de la salud de conformidad con lo documentado en el estándar de procesos prioritarios.', 645, '1.2', 91, '1.2. Cuando se realicen pruebas complementarias de tamización (audiometría, visiometría, espirometría según aplique), disponibilidad de profesionales de la salud de conformidad con lo documentado en el estándar de procesos prioritarios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Talento Humano', 'mediana', 'intramural, extramural unidad móvil y jornada de salud'),
  ('2;2. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente:', 646, '2', 91, '2. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Talento Humano', 'mediana', 'telemedicina - prestador remisor'),
  ('2.1;2.1. Cuando se realice telexperticia entre profesionales de la salud cuenta con el profesional de la salud.', 647, '2.1', 91, '2.1. Cuando se realice telexperticia entre profesionales de la salud cuenta con el profesional de la salud.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Talento Humano', 'mediana', 'telemedicina - prestador remisor'),
  ('3;3. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con: Profesional en salud según la oferta definida por el prestador de servicios de salud en el estándar de procesos prioritarios.', 648, '3', 91, '3. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con: Profesional en salud según la oferta definida por el prestador de servicios de salud en el estándar de procesos prioritarios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Talento Humano', 'mediana', 'telemedicina - prestador de referencia'),
  ('4;4. Cumple con los criterios definidos del servicio de consulta externa para consultorio donde se realiza examen físico.', 649, '4', 91, '4. Cumple con los criterios definidos del servicio de consulta externa para consultorio donde se realiza examen físico.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Infraestructura', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('5;5. Cumple con los criterios que le sean aplicables de todos los servicios.', 650, '5', 91, '5. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Infraestructura', 'mediana', 'telemedicina - prestador de referencia'),
  ('6;6. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente:', 651, '6', 92, '6. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('7;7. El consultorio, cuenta con:', 652, '7', 92, '7. El consultorio, cuenta con:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('7.1;7.1. Camilla fija.', 653, '7.1', 92, '7.1. Camilla fija.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('7.2;7.2. Escalerilla.', 654, '7.2', 92, '7.2. Escalerilla.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('7.3;7.3. Tensiómetro.', 655, '7.3', 92, '7.3. Tensiómetro.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('7.4;7.4. Fonendoscopio.', 656, '7.4', 92, '7.4. Fonendoscopio.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('7.5;7.5. Equipo de órganos de los sentidos.', 657, '7.5', 92, '7.5. Equipo de órganos de los sentidos.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('7.6;7.6. Martillo de reflejos.', 658, '7.6', 92, '7.6. Martillo de reflejos.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('7.7;7.7. Tallímetro', 659, '7.7', 92, '7.7. Tallímetro', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('7.8;7.8. Cinta métrica.', 660, '7.8', 92, '7.8. Cinta métrica.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('7.9;7.9. Báscula.', 661, '7.9', 92, '7.9. Báscula.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('7.10;7.10. Termómetro.', 662, '7.10', 92, '7.10. Termómetro.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('7.11;7.11. Negatoscopio cuando se requiera o sistema de visualización según la tecnología utilizada por el prestador.', 663, '7.11', 92, '7.11. Negatoscopio cuando se requiera o sistema de visualización según la tecnología utilizada por el prestador.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('8;8. Para la realización de pruebas complementarias de tamización (audiometría, visiometría, espirometría), cuenta con la dotación y los equipos biomédicos necesarios de acuerdo con lo documentado en el estándar de procesos prioritarios.', 664, '8', 92, '8. Para la realización de pruebas complementarias de tamización (audiometría, visiometría, espirometría), cuenta con la dotación y los equipos biomédicos necesarios de acuerdo con lo documentado en el estándar de procesos prioritarios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina - prestador remisor'),
  ('9;9. Cumple con los criterios que le sean aplicables de todos los servicios.', 665, '9', 92, '9. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Dotación', 'mediana', 'telemedicina – prestador de referencia'),
  ('10;10. Cumple con los criterios que le sean aplicables de todos los servicios.', 666, '10', 92, '10. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Medicamentos, Dispositivos Médicos e Insumos', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina – prestador remisor y prestador de referencia'),
  ('11;11. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con la siguiente información documentada:
Pruebas complementarias de tamización documentadas (audiometría, visiometría, espirometría), cuando se realicen.', 667, '11', 93, '11. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con la siguiente información documentada:
Pruebas complementarias de tamización documentadas (audiometría, visiometría, espirometría), cuando se realicen.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Procesos Prioritarios', 'mediana', 'intramural y extramural unidad móvil, jornada de salud y telemedicina – prestador remisor'),
  ('12;12. Cumple con los criterios que le sean aplicables de todos los servicios.', 668, '12', 93, '12. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.4'), '11.2', '11.2.4', 'Estándar de Procesos Prioritarios', 'mediana', 'telemedicina - prestador de referencia');
