insert into criterios_res3100 (llave, numero, item, pagina, criterio, grupo_res3100_id, servicio_res3100_id, numeral_grupo, numeral_servicio, estandar, complejidad, modalidad) values
  ('13;13. Las Instituciones Prestadoras de Servicios de Salud con servicios en la modalidad intramural para Hospitalización, hospitalización paciente crónico con y sin ventilador, cuidados intensivos neonatales, pediátricos y adultos, urgencias y servicios del grupo quirúrgico, cuentan con:', 457, '13', 78, '13. Las Instituciones Prestadoras de Servicios de Salud con servicios en la modalidad intramural para Hospitalización, hospitalización paciente crónico con y sin ventilador, cuidados intensivos neonatales, pediátricos y adultos, urgencias y servicios del grupo quirúrgico, cuentan con:', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'intramural, extramural: unidad móvil, domiciliaria, jornada de salud y telemedicina prestador remisor - prestador de referencia'),
  ('13.1;13.1. Registro de donantes detectados.', 458, '13.1', 78, '13.1. Registro de donantes detectados.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'intramural, extramural: unidad móvil, domiciliaria, jornada de salud y telemedicina prestador remisor - prestador de referencia'),
  ('13.2;13.2. Registro de consulta del documento de voluntad anticipada de todos los pacientes fallecidos.', 459, '13.2', 78, '13.2. Registro de consulta del documento de voluntad anticipada de todos los pacientes fallecidos.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'intramural, extramural: unidad móvil, domiciliaria, jornada de salud y telemedicina prestador remisor - prestador de referencia'),
  ('13.3;13.3. Registros en la historia clínica de la información sobre el proceso de donación efectuado por los profesionales de salud inscritos ante el Instituto Nacional de Salud.', 460, '13.3', 78, '13.3. Registros en la historia clínica de la información sobre el proceso de donación efectuado por los profesionales de salud inscritos ante el Instituto Nacional de Salud.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'intramural, extramural: unidad móvil, domiciliaria, jornada de salud y telemedicina prestador remisor - prestador de referencia'),
  ('14;14. La historia clínica utilizada en la modalidad extramural es custodiada por el prestador de servicios de salud que oferta y presta el servicio de salud en la modalidad extramural y cuenta con los siguientes registros:', 461, '14', 78, '14. La historia clínica utilizada en la modalidad extramural es custodiada por el prestador de servicios de salud que oferta y presta el servicio de salud en la modalidad extramural y cuenta con los siguientes registros:', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'extramural'),
  ('15;15. Documento firmado por un ingeniero de sistemas con tarjeta profesional vigente, que certifique:', 462, '15', 78, '15. Documento firmado por un ingeniero de sistemas con tarjeta profesional vigente, que certifique:', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'telemedicina - Prestador Remisor - Prestador de Referencia Cuenta con:'),
  ('15.1;15.1. Los mecanismos que garanticen la custodia, seguridad confidencialidad y conservación integral, durante la transmisión y almacenamiento de la información contenida en la historia clínica y demás registros asistenciales y la reproducibilidad de la información de acuerdo con la legislación vigente.', 463, '15.1', 78, '15.1. Los mecanismos que garanticen la custodia, seguridad confidencialidad y conservación integral, durante la transmisión y almacenamiento de la información contenida en la historia clínica y demás registros asistenciales y la reproducibilidad de la información de acuerdo con la legislación vigente.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'telemedicina - Prestador Remisor - Prestador de Referencia Cuenta con:'),
  ('15.2;15.2. Los mecanismos de compresión utilizados por el prestador para que la información recuperada corresponda al dato, imagen o señal original (compresión sin pérdidas).', 464, '15.2', 78, '15.2. Los mecanismos de compresión utilizados por el prestador para que la información recuperada corresponda al dato, imagen o señal original (compresión sin pérdidas).', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'telemedicina - Prestador Remisor - Prestador de Referencia Cuenta con:'),
  ('15.3;15.3. El método utilizado para el uso de la firma electrónica o digital.', 465, '15.3', 78, '15.3. El método utilizado para el uso de la firma electrónica o digital.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'telemedicina - Prestador Remisor - Prestador de Referencia Cuenta con:'),
  ('15.4;15.4. La encriptación de la información para su transmisión y mecanismos de acceso a la misma de acuerdo con lo definido por el prestador de servicios de salud.', 466, '15.4', 78, '15.4. La encriptación de la información para su transmisión y mecanismos de acceso a la misma de acuerdo con lo definido por el prestador de servicios de salud.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'telemedicina - Prestador Remisor - Prestador de Referencia Cuenta con:'),
  ('15.5;15.5. Los sistemas de seguridad y control de acceso a la aplicación, según tipo de usuario. cuando se utilizan sistemas de información compartidos o de acceso remoto.', 467, '15.5', 78, '15.5. Los sistemas de seguridad y control de acceso a la aplicación, según tipo de usuario. cuando se utilizan sistemas de información compartidos o de acceso remoto.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'telemedicina - Prestador Remisor - Prestador de Referencia Cuenta con:'),
  ('16;16. Plan de contingencia en caso de fallas del sistema activo o pérdida de datos.', 468, '16', 78, '16. Plan de contingencia en caso de fallas del sistema activo o pérdida de datos.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'telemedicina - Prestador Remisor - Prestador de Referencia Cuenta con:'),
  ('17;17. Todos los eventos y transacciones que se realicen con ocasión de la prestación de servicios en la modalidad de telemedicina son documentados y almacenados, y son parte integral de la historia clínica.', 469, '17', 78, '17. Todos los eventos y transacciones que se realicen con ocasión de la prestación de servicios en la modalidad de telemedicina son documentados y almacenados, y son parte integral de la historia clínica.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'telemedicina - Prestador Remisor - Prestador de Referencia Cuenta con:'),
  ('18;18. Registro de las atenciones realizadas en la modalidad de telemedicina.', 470, '18', 78, '18. Registro de las atenciones realizadas en la modalidad de telemedicina.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.6', 'Estándar de Historia Clínica y Registros', 'Todas', 'telemedicina - Prestador Remisor - Prestador de Referencia Cuenta con:'),
  ('1;1. Cuando el servicio interdependiente sea contratado, debe mediar un contrato o un acuerdo escrito entre las dos partes, en el que se establezca que el servicio interdependiente apoya el servicio principal, estableciendo como mínimo:
1.1 Calidad en la entrega de los productos.
1.2 Procedimientos documentados de atención en cada servicio interdependiente.
1.3 Tiempos de entrega de los productos.
1.4 Supervisión al contratista que garantice la seguridad del resultado del producto contratado.', 471, '1', 79, '1. Cuando el servicio interdependiente sea contratado, debe mediar un contrato o un acuerdo escrito entre las dos partes, en el que se establezca que el servicio interdependiente apoya el servicio principal, estableciendo como mínimo:
1.1 Calidad en la entrega de los productos.
1.2 Procedimientos documentados de atención en cada servicio interdependiente.
1.3 Tiempos de entrega de los productos.
1.4 Supervisión al contratista que garantice la seguridad del resultado del producto contratado.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.7', 'Estándar de Interdependencia', 'Todas', 'Todas'),
  ('2;2. Cuando fuera de salas de cirugía, se realicen procedimientos bajo sedación y monitorización electroencefalográfica con video y radio; el prestador de servicios de salud tiene disponibilidad del servicio de transporte asistencial.', 472, '2', 79, '2. Cuando fuera de salas de cirugía, se realicen procedimientos bajo sedación y monitorización electroencefalográfica con video y radio; el prestador de servicios de salud tiene disponibilidad del servicio de transporte asistencial.', (select id from grupos_res3100 where numeral = '11.1'), (select id from servicios_res3100 where numeral = '11.1'), '11.1', '11.1.7', 'Estándar de Interdependencia', 'Todas', 'Todas'),
  ('1;1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente,', 473, '1', 80, '1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente,', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Talento Humano', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('2;2. Cuenta con el profesional de la salud de acuerdo con el servicio a ofertar.', 474, '2', 80, '2. Cuenta con el profesional de la salud de acuerdo con el servicio a ofertar.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Talento Humano', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('3;3. Cuando se oferte la estrategia para el manejo de la Enfermedad Respiratoria Aguda (ERA), el servicio tiene disponibilidad de:', 475, '3', 80, '3. Cuando se oferte la estrategia para el manejo de la Enfermedad Respiratoria Aguda (ERA), el servicio tiene disponibilidad de:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Talento Humano', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('3.1;3.1. Profesional de la medicina.', 476, '3.1', 80, '3.1. Profesional de la medicina.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Talento Humano', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('3.2;3.2. Profesional de la enfermería o terapia respiratoria o fisioterapia.', 477, '3.2', 80, '3.2. Profesional de la enfermería o terapia respiratoria o fisioterapia.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Talento Humano', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('4;4. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con:', 478, '4', 80, '4. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Talento Humano', 'baja', 'telemedicina - Categoría interactiva y no interactiva – prestador de referencia'),
  ('4.1;4.1. Profesional de la salud de acuerdo con el servicio a ofertar.', 479, '4.1', 80, '4.1. Profesional de la salud de acuerdo con el servicio a ofertar.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Talento Humano', 'baja', 'telemedicina - Categoría interactiva y no interactiva – prestador de referencia'),
  ('5;5. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente:', 480, '5', 80, '5. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Talento Humano', 'baja', 'telemedicina - Categoría telexperticia - prestador remisor'),
  ('5.1;5.1. Cuando se realice telexperticia entre profesionales de la salud cuenta con el profesional de la salud de acuerdo con el servicio a ofertar.', 481, '5.1', 80, '5.1. Cuando se realice telexperticia entre profesionales de la salud cuenta con el profesional de la salud de acuerdo con el servicio a ofertar.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Talento Humano', 'baja', 'telemedicina - Categoría telexperticia - prestador remisor'),
  ('5.2;5.2. Cuando realice telexperticia entre personal de salud no profesional y un profesional de la salud, el prestador remisor cuenta con técnico, tecnólogo o auxiliar que atiende presencialmente al usuario.', 482, '5.2', 80, '5.2. Cuando realice telexperticia entre personal de salud no profesional y un profesional de la salud, el prestador remisor cuenta con técnico, tecnólogo o auxiliar que atiende presencialmente al usuario.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Talento Humano', 'baja', 'telemedicina - Categoría telexperticia - prestador remisor'),
  ('6;6. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con profesional de la salud que atiende a distancia, de acuerdo con el servicio a ofertar.', 483, '6', 80, '6. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con profesional de la salud que atiende a distancia, de acuerdo con el servicio a ofertar.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Talento Humano', 'baja', 'telemedicina - Categoría telexperticia - prestador de referencia'),
  ('7;7. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con el personal de salud profesional que se requiera para realizar el telemonitoreo de acuerdo con lo documentado por el prestador de servicios de salud en el estándar de procesos prioritarios.', 484, '7', 80, '7. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con el personal de salud profesional que se requiera para realizar el telemonitoreo de acuerdo con lo documentado por el prestador de servicios de salud en el estándar de procesos prioritarios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Talento Humano', 'baja', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('8;8. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente,', 485, '8', 80, '8. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente,', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('9;9. Cuenta con:', 486, '9', 80, '9. Cuenta con:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('9.1;9.1. El tipo de ambiente o consultorio de acuerdo con la oferta, así:', 487, '9.1', 80, '9.1. El tipo de ambiente o consultorio de acuerdo con la oferta, así:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('9.1.1;9.1.1. Consultorio donde se realiza examen físico.', 488, '9.1.1', 80, '9.1.1. Consultorio donde se realiza examen físico.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('9.1.2;9.1.2. Ambiente de entrevista donde no se realiza examen físico ni procedimientos. 9.1.3. Consultorio donde se realizan procedimientos.', 489, '9.1.2', 80, '9.1.2. Ambiente de entrevista donde no se realiza examen físico ni procedimientos. 9.1.3. Consultorio donde se realizan procedimientos.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('9.1.4;9.1.4. Consultorio odontológico con una unidad odontológica o más.', 490, '9.1.4', 80, '9.1.4. Consultorio odontológico con una unidad odontológica o más.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('9.2;9.2. Sala de procedimientos, cuando se requiera.', 491, '9.2', 80, '9.2. Sala de procedimientos, cuando se requiera.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('10;10. Disponibilidad de:', 492, '10', 81, '10. Disponibilidad de:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('10.1;10.1. Sala de espera.', 493, '10.1', 81, '10.1. Sala de espera.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('10.2;10.2. Mínimo una (1) unidad sanitaria de uso mixto, apta para personas con movilidad reducida, cuando el prestador cuente con hasta dos consultorios o ambientes de entrevista.', 494, '10.2', 81, '10.2. Mínimo una (1) unidad sanitaria de uso mixto, apta para personas con movilidad reducida, cuando el prestador cuente con hasta dos consultorios o ambientes de entrevista.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('10.3;10.3. Mínimo una (1) unidad sanitaria discriminada por sexo apta para personas con movilidad reducida, o batería sanitaria discriminada por sexo con mínimo una (1) unidad sanitaria apta para personas con movilidad reducida, cuando el prestador cuente con más de dos consultorios o ambientes de entrevista.', 495, '10.3', 81, '10.3. Mínimo una (1) unidad sanitaria discriminada por sexo apta para personas con movilidad reducida, o batería sanitaria discriminada por sexo con mínimo una (1) unidad sanitaria apta para personas con movilidad reducida, cuando el prestador cuente con más de dos consultorios o ambientes de entrevista.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('11;11. Cuando se oferte la estrategia para el manejo de la Enfermedad Respiratoria Aguda (ERA), el ambiente cuenta con:', 496, '11', 81, '11. Cuando se oferte la estrategia para el manejo de la Enfermedad Respiratoria Aguda (ERA), el ambiente cuenta con:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.1'), '11.2', '11.2.1', 'Estándar de Infraestructura', 'baja', 'intramural');
