insert into criterios_res3100 (llave, numero, item, pagina, criterio, grupo_res3100_id, servicio_res3100_id, numeral_grupo, numeral_servicio, estandar, complejidad, modalidad) values
  ('11;11. Cumple con los criterios que le sean aplicables de todos los servicios.', 590, '11', 86, '11. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Infraestructura', 'mediana', 'telemedicina - Categoría telexperticia - prestador de referencia'),
  ('12;12. Cumple con los criterios que le sean aplicables de todos los servicios.', 591, '12', 86, '12. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Infraestructura', 'mediana', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('13;13. Cumple con los criterios definidos para el servicio de consulta externa general y adicionalmente: Los consultorios de los especialistas cuentan con la dotación necesaria para realizar los procedimientos documentados en el estándar de procesos prioritarios.', 592, '13', 86, '13. Cumple con los criterios definidos para el servicio de consulta externa general y adicionalmente: Los consultorios de los especialistas cuentan con la dotación necesaria para realizar los procedimientos documentados en el estándar de procesos prioritarios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Dotación', 'mediana', 'intramural, extramural: unidad móvil, jornada de salud y domiciliaria'),
  ('14;14. Cumple con los criterios que le sean aplicables de todos los servicios. Categoría telexperticia - prestador remisor', 593, '14', 86, '14. Cumple con los criterios que le sean aplicables de todos los servicios. Categoría telexperticia - prestador remisor', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Dotación', 'mediana', 'telemedicina - Categoría interactiva y no interactiva – prestador de referencia'),
  ('15;15. Cumple con los criterios que le sean aplicables de todos los servicios y los establecidos en el servicio de consulta externa especializada.', 594, '15', 86, '15. Cumple con los criterios que le sean aplicables de todos los servicios y los establecidos en el servicio de consulta externa especializada.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Dotación', 'mediana', 'telemedicina - Categoría interactiva y no interactiva – prestador de referencia'),
  ('16;16. Cumple con los criterios que le sean aplicables de todos los servicios.', 595, '16', 86, '16. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Dotación', 'mediana', 'telemedicina - Categoría telexperticia - prestador de referencia'),
  ('17;17. Cumple con los criterios que le sean aplicables de todos los servicios.', 596, '17', 86, '17. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Dotación', 'mediana', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('18;18. Cumple con los criterios que le sean aplicables de todos los servicios.', 597, '18', 86, '18. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Medicamentos, Dispositivos Médicos e Insumos', 'mediana', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('19;19. Cumple con los criterios que le sean aplicables de todos los servicios.', 598, '19', 86, '19. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Medicamentos, Dispositivos Médicos e Insumos', 'mediana', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('20;20. Cumple con los criterios definidos para el servicio de consulta externa general.', 599, '20', 86, '20. Cumple con los criterios definidos para el servicio de consulta externa general.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Procesos Prioritarios', 'mediana', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('21;21. Adicionalmente para el caso de medicina y terapias alternativas y complementarias, cuenta con información documentada de:', 600, '21', 87, '21. Adicionalmente para el caso de medicina y terapias alternativas y complementarias, cuenta con información documentada de:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Procesos Prioritarios', 'mediana', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('21.1;21.1. Criterios explícitos y documentados sobre el tipo de procedimientos que se pueden realizar y de los que no se pueden realizar teniendo como marco el ámbito de la competencia.', 601, '21.1', 87, '21.1. Criterios explícitos y documentados sobre el tipo de procedimientos que se pueden realizar y de los que no se pueden realizar teniendo como marco el ámbito de la competencia.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Procesos Prioritarios', 'mediana', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('21.2;21.2. Procedimientos para la información al paciente sobre preparación y recomendaciones post procedimiento, controles, posibles complicaciones y disponibilidad de consulta permanente y en general las previsiones que se requieran para proteger al paciente de los riesgos de procedimientos que se realicen en la consulta.', 602, '21.2', 87, '21.2. Procedimientos para la información al paciente sobre preparación y recomendaciones post procedimiento, controles, posibles complicaciones y disponibilidad de consulta permanente y en general las previsiones que se requieran para proteger al paciente de los riesgos de procedimientos que se realicen en la consulta.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Procesos Prioritarios', 'mediana', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('22;22. Cumple con los criterios que le sean aplicables de todos los servicios.', 603, '22', 87, '22. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Procesos Prioritarios', 'mediana', 'telemedicina - Categoría interactiva y no interactiva – prestador de referencia'),
  ('23;23. Cumple con los criterios que le sean aplicables de todos los servicios y los establecidos en el servicio de consulta externa especializada.', 604, '23', 87, '23. Cumple con los criterios que le sean aplicables de todos los servicios y los establecidos en el servicio de consulta externa especializada.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Procesos Prioritarios', 'mediana', 'telemedicina - Categoría telexperticia - prestador remisor'),
  ('24;24. Cumple con los criterios que le sean aplicables de todos los servicios.', 605, '24', 87, '24. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Procesos Prioritarios', 'mediana', 'telemedicina - Categoría telexperticia - prestador de referencia'),
  ('25;25. Cumple con los criterios que le sean aplicables de todos los servicios.', 606, '25', 87, '25. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Procesos Prioritarios', 'mediana', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('26;26. Cumple con los criterios que le sean aplicables de todos los servicios.', 607, '26', 87, '26. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Historia Clínica y Registros', 'mediana', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('27;27. Cumple con los criterios que le sean aplicables de todos los servicios.', 608, '27', 87, '27. Cumple con los criterios que le sean aplicables de todos los servicios.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Historia Clínica y Registros', 'mediana', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('28;28. No aplica para la consulta externa médica especializada.', 609, '28', 87, '28. No aplica para la consulta externa médica especializada.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Interdependencia', 'mediana', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria y telemedicina'),
  ('29;29. Para la consulta odontológica especializada disponibilidad de:', 610, '29', 87, '29. Para la consulta odontológica especializada disponibilidad de:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Interdependencia', 'mediana', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria y telemedicina'),
  ('29.1;29.1. Servicio de radiología odontológica', 611, '29.1', 87, '29.1. Servicio de radiología odontológica', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Interdependencia', 'mediana', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria y telemedicina'),
  ('29.2;29.2. Transporte asistencial cuando se realicen procedimientos bajo sedación grado I y II.', 612, '29.2', 87, '29.2. Transporte asistencial cuando se realicen procedimientos bajo sedación grado I y II.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Interdependencia', 'mediana', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria y telemedicina'),
  ('30;30. No aplica', 613, '30', 87, '30. No aplica', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.2'), '11.2', '11.2.2', 'Estándar de Interdependencia', 'mediana', 'telemedicina - Categoría telemonitoreo - prestador de referencia'),
  ('1;1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con:
1.1 Profesional de la medicina o profesional de la enfermería.', 614, '1', 88, '1. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente, cuenta con:
1.1 Profesional de la medicina o profesional de la enfermería.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Talento Humano', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('2;2. Si se requiere personal adicional para:
2.1 La administración de la vacuna cuenta con auxiliar de enfermería o auxiliar de salud pública bajo la supervisión del profesional de la medicina o profesional de la enfermería.
2.2 El manejo de la cadena de frío puede disponer de auxiliar de enfermería o auxiliar en salud pública o gestor comunitario en salud (en zonas de dispersión geográfica) o regentes de farmacia o químico farmacéutico con experiencia en cadena de frío.', 615, '2', 88, '2. Si se requiere personal adicional para:
2.1 La administración de la vacuna cuenta con auxiliar de enfermería o auxiliar de salud pública bajo la supervisión del profesional de la medicina o profesional de la enfermería.
2.2 El manejo de la cadena de frío puede disponer de auxiliar de enfermería o auxiliar en salud pública o gestor comunitario en salud (en zonas de dispersión geográfica) o regentes de farmacia o químico farmacéutico con experiencia en cadena de frío.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Talento Humano', 'baja', 'intramural, extramural unidad móvil, jornada de salud y domiciliaria'),
  ('3;3. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:', 616, '3', 88, '3. Cumple con los criterios que le sean aplicables de todos los servicios y adicionalmente cuenta con:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4;4. Consultorio o ambiente que, de acuerdo con la oferta, cumple con los siguientes requisitos:
Para los servicios en modalidad intramural de prestadores de servicios de salud que separen el servicio de vacunación en dos ambientes cuenta con:
4.1 Consultorio para administración de medicamentos biológicos que cuenta con:', 617, '4', 88, '4. Consultorio o ambiente que, de acuerdo con la oferta, cumple con los siguientes requisitos:
Para los servicios en modalidad intramural de prestadores de servicios de salud que separen el servicio de vacunación en dos ambientes cuenta con:
4.1 Consultorio para administración de medicamentos biológicos que cuenta con:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.1;4.1.1 Área para entrevista.', 618, '4.1', 88, '4.1.1 Área para entrevista.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.1;4.1.2 Área para el alistamiento y administración de medicamentos biológicos.', 619, '4.1', 88, '4.1.2 Área para el alistamiento y administración de medicamentos biológicos.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.1;4.1.3 Lavamanos.
4.2 Ambiente para almacenamiento y alistamiento de dispositivos y termos que cuenta con:', 620, '4.1', 88, '4.1.3 Lavamanos.
4.2 Ambiente para almacenamiento y alistamiento de dispositivos y termos que cuenta con:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.2;4.2.1 Área para el alistamiento de termos o cajas térmicas.', 621, '4.2', 88, '4.2.1 Área para el alistamiento de termos o cajas térmicas.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.2;4.2.2 Área de cadena de frío que incluye un mesón con poceta, con capacidad para el lavado de termos, con grifo cuello de cisne o ducha teléfono; que puede estar ubicado en otro ambiente diferente al consultorio.', 622, '4.2', 88, '4.2.2 Área de cadena de frío que incluye un mesón con poceta, con capacidad para el lavado de termos, con grifo cuello de cisne o ducha teléfono; que puede estar ubicado en otro ambiente diferente al consultorio.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.2;4.2.3 Área para el almacenamiento de dispositivos médicos e insumos, que puede estar ubicado en otro ambiente diferente al consultorio.', 623, '4.2', 88, '4.2.3 Área para el almacenamiento de dispositivos médicos e insumos, que puede estar ubicado en otro ambiente diferente al consultorio.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.2;4.2.4 Lavamanos.
4.3 Disponibilidad de:', 624, '4.2', 88, '4.2.4 Lavamanos.
4.3 Disponibilidad de:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.3;4.3.1 Sala de espera.', 625, '4.3', 88, '4.3.1 Sala de espera.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.3;4.3.2 Unidades sanitarias discriminadas por sexo.
Para los servicios en modalidad intramural de prestadores de servicios de salud que integren en un solo ambiente el servicio de vacunación cuenta con:
4.4 Ambiente de vacunación, para administración de medicamentos biológicos, que cuenta con:', 626, '4.3', 88, '4.3.2 Unidades sanitarias discriminadas por sexo.
Para los servicios en modalidad intramural de prestadores de servicios de salud que integren en un solo ambiente el servicio de vacunación cuenta con:
4.4 Ambiente de vacunación, para administración de medicamentos biológicos, que cuenta con:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.4;4.4.1 Área para entrevista.', 627, '4.4', 88, '4.4.1 Área para entrevista.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.4;4.4.2 Área para el alistamiento y administración de medicamentos biológicos.', 628, '4.4', 88, '4.4.2 Área para el alistamiento y administración de medicamentos biológicos.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.4;4.4.3 Área para el alistamiento de termos o cajas térmicas.', 629, '4.4', 88, '4.4.3 Área para el alistamiento de termos o cajas térmicas.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.4;4.4.4 Área de cadena de frío que incluye un mesón con poceta, con capacidad para el lavado de los termos, con grifo cuello de cisne o ducha teléfono, que puede estar ubicado en otro ambiente diferente al consultorio.', 630, '4.4', 88, '4.4.4 Área de cadena de frío que incluye un mesón con poceta, con capacidad para el lavado de los termos, con grifo cuello de cisne o ducha teléfono, que puede estar ubicado en otro ambiente diferente al consultorio.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.4;4.4.5 Área para el almacenamiento de dispositivos médicos e insumos, que puede estar ubicado en otro ambiente diferente al consultorio.', 631, '4.4', 88, '4.4.5 Área para el almacenamiento de dispositivos médicos e insumos, que puede estar ubicado en otro ambiente diferente al consultorio.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.4;4.4.6 Lavamanos.
4.5 Disponibilidad de:', 632, '4.4', 88, '4.4.6 Lavamanos.
4.5 Disponibilidad de:', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural'),
  ('4.5;4.5.1 Sala de espera.', 633, '4.5', 88, '4.5.1 Sala de espera.', (select id from grupos_res3100 where numeral = '11.2'), (select id from servicios_res3100 where numeral = '11.2.3'), '11.2', '11.2.3', 'Estándar de Infraestructura', 'baja', 'intramural');
